#BERTopic on UNTM Datasets
In this notebook we have performed hyper-parameter tuning on Urdu News Data using a bert based topic modelling technique BERTopic.

## Mounting Google Drive
If the dataset is on Google Drive then you have to mount over google drive with collaboratory.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive



#Installing required dependencies
**One thing to remember is that after installing libraries you have to restart the run time again so that other dependencies are not affected by it.**

In [ ]:
!pip install bertopic

Collecting bertopic
  Downloading bertopic-0.16.0-py2.py3-none-any.whl (154 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.1/154.1 kB 2.5 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.10/dist-packages (from bertopic) (1.23.5)
Collecting hdbscan>=0.8.29 (from bertopic)
  Downloading hdbscan-0.8.33.tar.gz (5.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 9.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting umap-learn>=0.5.0 (from bertopic)
  Downloading umap-learn-0.5.5.tar.gz (90 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.9/90.9 kB 9.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pandas>=1.1.5 in /usr/local/lib/python3.10/dist-packages (from bertopic) (1.5.3)
Requirement already satisfied: scikit-learn>=0.22.2.post1 in /usr/local/lib/python3.10/dist-packages (from bertopic) (1.2.2)
Requirement already satisfied: tqdm>=4.41.1 in /usr/local/lib/python3.10/dist-packages (from bertopic) (4.66.1)
Collecting sentence-transformers>=0.4.1 (from bertopic)
  Downloading sentence-transformers-2.2.2.tar.gz (85 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 kB 9.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: plotly>=4.7.0 in /usr/local/lib/python3.10/dist-packages (from bertopic) (5.15.0)
Collecting cython<3,>=0.27 (from hdbscan>=0.8.29->bertopic)
  Using cached Cython-0.29.36-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (1.9 MB)
Requirement already satisfied: scipy>=1.0 in /usr/local/lib/python3.10/dist-packages (from hdbscan>=0.8.29->bertopic) (1.11.3)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.10/dist-packages (from hdbscan>=0.8.29->bertopic) (1.3.2)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.1.5->bertopic) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.1.5->bertopic) (2023.3.post1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from plotly>=4.7.0->bertopic) (8.2.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from plotly>=4.7.0->bertopic) (23.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.22.2.post1->bertopic) (3.2.0)
Requirement already satisfied: transformers<5.0.0,>=4.6.0 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers>=0.4.1->bertopic) (4.35.2)
Requirement already satisfied: torch>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers>=0.4.1->bertopic) (2.1.0+cu118)
Requirement already satisfied: torchvision in /usr/local/lib/python3.10/dist-packages (from sentence-transformers>=0.4.1->bertopic) (0.16.0+cu118)
Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (from sentence-transformers>=0.4.1->bertopic) (3.8.1)
Collecting sentencepiece (from sentence-transformers>=0.4.1->bertopic)
  Downloading sentencepiece-0.1.99-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 26.9 MB/s eta 0:00:00
Requirement already satisfied: huggingface-hub>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers>=0.4.1->bertopic) (0.19.4)
Requirement already satisfied: numba>=0.51.2 in /usr/local/lib/python3.10/dist-packages (from umap-learn>=0.5.0->bertopic) (0.58.1)
Collecting pynndescent>=0.5 (from umap-learn>=0.5.0->bertopic)
  Downloading pynndescent-0.5.11-py3-none-any.whl (55 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.8/55.8 kB 6.2 MB/s eta 0:00:00
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence-transformers>=0.4.1->bertopic) (3.13.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence-transformers>=0.4.1->bertopic) (2023.6.0)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence-transformers>=0.4.1->bertopic) (2.31.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence-transformers>=0.4.1->bertopic) (6.0.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence-transformers>=0.4.1->bertopic) (4.5.0)
Requirement already satisfied: llvmlite<0.42,>=0.41.0dev0 in /usr/local/lib/python3.10/dist-packages (from numba>=0.51.2->umap-learn>=0.5.0->bertopic) (0.41.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas>=1.1.5->bertopic) (1.16.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->sentence-transformers>=0.4.1->bertopic) (1.12)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->sentence-transformers>=0.4.1->bertopic) (3.2.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->sentence-transformers>=0.4.1->bertopic) (3.1.2)
Requirement already satisfied: triton==2.1.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->sentence-transformers>=0.4.1->bertopic) (2.1.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.6.0->sentence-transformers>=0.4.1->bertopic) (2023.6.3)
Requirement already satisfied: tokenizers<0.19,>=0.14 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.6.0->sentence-transformers>=0.4.1->bertopic) (0.15.0)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.6.0->sentence-transformers>=0.4.1->bertopic) (0.4.0)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk->sentence-transformers>=0.4.1->bertopic) (8.1.7)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.10/dist-packages (from torchvision->sentence-transformers>=0.4.1->bertopic) (9.4.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.6.0->sentence-transformers>=0.4.1->bertopic) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.4.0->sentence-transformers>=0.4.1->bertopic) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.4.0->sentence-transformers>=0.4.1->bertopic) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.4.0->sentence-transformers>=0.4.1->bertopic) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.4.0->sentence-transformers>=0.4.1->bertopic) (2023.7.22)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.6.0->sentence-transformers>=0.4.1->bertopic) (1.3.0)
Building wheels for collected packages: hdbscan, sentence-transformers, umap-learn
  Building wheel for hdbscan (pyproject.toml) ... done
  Created wheel for hdbscan: filename=hdbscan-0.8.33-cp310-cp310-linux_x86_64.whl size=3039181 sha256=f37fe05d923082d79c2f749ade73e29e1b536066f51b996d6f3db56a73e9cd19
  Stored in directory: /root/.cache/pip/wheels/75/0b/3b/dc4f60b7cc455efaefb62883a7483e76f09d06ca81cf87d610
  Building wheel for sentence-transformers (setup.py) ... done
  Created wheel for sentence-transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125923 sha256=59c99fe7d6d3d0f7ca0aaca3434ce6a5b238908621980552c62c660a06e23cff
  Stored in directory: /root/.cache/pip/wheels/62/f2/10/1e606fd5f02395388f74e7462910fe851042f97238cbbd902f
  Building wheel for umap-learn (setup.py) ... done
  Created wheel for umap-learn: filename=umap_learn-0.5.5-py3-none-any.whl size=86831 sha256=7313b4d459fa025c3609e59f931355541c82ed9e722bb28412f34bdbe09ef3d5
  Stored in directory: /root/.cache/pip/wheels/3a/70/07/428d2b58660a1a3b431db59b806a10da736612ebbc66c1bcc5
Successfully built hdbscan sentence-transformers umap-learn
Installing collected packages: sentencepiece, cython, pynndescent, hdbscan, umap-learn, sentence-transformers, bertopic
  Attempting uninstall: cython
    Found existing installation: Cython 3.0.5
    Uninstalling Cython-3.0.5:
      Successfully uninstalled Cython-3.0.5
Successfully installed bertopic-0.16.0 cython-0.29.36 hdbscan-0.8.33 pynndescent-0.5.11 sentence-transformers-2.2.2 sentencepiece-0.1.99 umap-learn-0.5.5

In [ ]:
!pip install -U sentence-transformers

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.10/dist-packages (2.2.2)
Requirement already satisfied: transformers<5.0.0,>=4.6.0 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (4.35.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (4.66.1)
Requirement already satisfied: torch>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (2.1.0+cu118)
Requirement already satisfied: torchvision in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (0.16.0+cu118)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (1.23.5)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (1.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (1.11.3)
Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (3.8.1)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (0.1.99)
Requirement already satisfied: huggingface-hub>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (0.19.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence-transformers) (3.13.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence-transformers) (2023.6.0)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence-transformers) (2.31.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence-transformers) (6.0.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence-transformers) (4.5.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence-transformers) (23.2)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->sentence-transformers) (1.12)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->sentence-transformers) (3.2.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->sentence-transformers) (3.1.2)
Requirement already satisfied: triton==2.1.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->sentence-transformers) (2.1.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.6.0->sentence-transformers) (2023.6.3)
Requirement already satisfied: tokenizers<0.19,>=0.14 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.6.0->sentence-transformers) (0.15.0)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.6.0->sentence-transformers) (0.4.0)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk->sentence-transformers) (8.1.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk->sentence-transformers) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->sentence-transformers) (3.2.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.10/dist-packages (from torchvision->sentence-transformers) (9.4.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.6.0->sentence-transformers) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.4.0->sentence-transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.4.0->sentence-transformers) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.4.0->sentence-transformers) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.4.0->sentence-transformers) (2023.7.22)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.6.0->sentence-transformers) (1.3.0)

In [ ]:
!pip install --upgrade tensorflow

Requirement already satisfied: tensorflow in /usr/local/lib/python3.10/dist-packages (2.12.0)
Collecting tensorflow
  Downloading tensorflow-2.15.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (475.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 475.2/475.2 MB 1.1 MB/s eta 0:00:00
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=23.5.26 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (23.5.26)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.4.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: h5py>=2.9.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (3.9.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (16.0.6)
Requirement already satisfied: ml-dtypes~=0.2.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: numpy<2.0.0,>=1.23.5 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.23.5)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from tensorflow) (23.2)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (3.20.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from tensorflow) (67.7.2)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (2.3.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (4.5.0)
Requirement already satisfied: wrapt<1.15,>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.14.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.34.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.59.2)
Collecting tensorboard<2.16,>=2.15 (from tensorflow)
  Downloading tensorboard-2.15.1-py3-none-any.whl (5.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 75.4 MB/s eta 0:00:00
Collecting tensorflow-estimator<2.16,>=2.15.0 (from tensorflow)
  Downloading tensorflow_estimator-2.15.0-py2.py3-none-any.whl (441 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 442.0/442.0 kB 37.2 MB/s eta 0:00:00
Collecting keras<2.16,>=2.15.0 (from tensorflow)
  Downloading keras-2.15.0-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 71.3 MB/s eta 0:00:00
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from astunparse>=1.6.0->tensorflow) (0.41.3)
Requirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow) (2.17.3)
Collecting google-auth-oauthlib<2,>=0.5 (from tensorboard<2.16,>=2.15->tensorflow)
  Downloading google_auth_oauthlib-1.1.0-py2.py3-none-any.whl (19 kB)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow) (3.5.1)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow) (2.31.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow) (3.0.1)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow) (5.3.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow) (0.3.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow) (1.3.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow) (2023.7.22)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.10/dist-packages (from werkzeug>=1.0.1->tensorboard<2.16,>=2.15->tensorflow) (2.1.3)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /usr/local/lib/python3.10/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow) (0.5.0)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow) (3.2.2)
Installing collected packages: tensorflow-estimator, keras, google-auth-oauthlib, tensorboard, tensorflow
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.12.0
    Uninstalling tensorflow-estimator-2.12.0:
      Successfully uninstalled tensorflow-estimator-2.12.0
  Attempting uninstall: keras
    Found existing installation: keras 2.12.0
    Uninstalling keras-2.12.0:
      Successfully uninstalled keras-2.12.0
  Attempting uninstall: google-auth-oauthlib
    Found existing installation: google-auth-oauthlib 0.4.6
    Uninstalling google-auth-oauthlib-0.4.6:
      Successfully uninstalled google-auth-oauthlib-0.4.6
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.12.0
    Uninstalling tensorboard-2.12.0:
      Successfully uninstalled tensorboard-2.12.0
  Attempting uninstall: tensorflow
    Found existing installation: tensorflow 2.12.0
    Uninstalling tensorflow-2.12.0:
      Successfully uninstalled tensorflow-2.12.0
Successfully installed google-auth-oauthlib-1.1.0 keras-2.15.0 tensorboard-2.15.1 tensorflow-2.15.0 tensorflow-estimator-2.15.0


# Importing required dependencies
We will import numpy, pandas and re, bertopic, gensim library for now. other libraries will be imported in the notebook later.

Pandas will be used to create a Dataframe and handle the csv file. Numpy will be used for the faster computation of arrays to save time. re library will be used for the cleaning of data. gensim library is used to get coherence score. Bertopic is used to train bertopic on our UNTM dataset with using pretrained language models

In [ ]:
import pandas as pd
import numpy as np
import re
from bertopic import BERTopic
from gensim.models.coherencemodel import CoherenceModel
import gensim.corpora as corpora
#optional
import logging
logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.ERROR)

import warnings
warnings.filterwarnings("ignore",category=DeprecationWarning)

##DataFrame
We scraped 8001 urdu news that consist of 7 categories=>Business,Technology, showbiz,Health,Politics,weird and Sports. After cleaning news, total 7991 rows saved into another new column Clean_Data for experiments.

In [ ]:
#load UNTM Dataset
df = pd.read_csv('/content/drive/MyDrive/Clean_UNTM.csv', encoding='utf-8')

In [ ]:
print(len(df))
df.head()

7991

,Date,Title,News,Category,Link,Clean_Data
0,2023-04-25,انوشکا شرما اور ویرات کوہلی کی بیڈ منٹن کھیلتے...,ممبئی(اُردو پوائنٹ اخبارتازہ ترین - آن لائن۔ 2...,Sports,https://www.urdupoint.com/sports/detail-news/l...,بھارتی کرکٹ کے آئیکون ویرات کوہلی اور انکی ...
1,2023-04-25,شکست کا ملبہ کسی پر بھی نہیں ڈالوں گا،بابراعظم,راولپنڈی(اُردو پوائنٹ اخبارتازہ ترین - آن لائن...,Sports,https://www.urdupoint.com/sports/detail-news/l...,پاکستان کرکٹ ٹیم کے کپتان بابر اعظم کا کہنا ...
2,2023-04-25,آئی پی ایل:سلواوورریٹ پر کوہلی کو بھاری جرمان...,نئی دہلی (اُردو پوائنٹ اخبارتازہ ترین - آن لائ...,Sports,https://www.urdupoint.com/sports/detail-news/l...,رائل چیلنجرز بنگلور کے کپتان ویرات کوہلی کو ا...
3,2023-04-25,ٹی ٹونٹی ایک مشکل فارمیٹ ہے ،جیت کیلئے اے گیم ...,راولپنڈی (اُردو پوائنٹ اخبارتازہ ترین - آن لائ...,Sports,https://www.urdupoint.com/sports/detail-news/l...,نیوزی لینڈ سے سیریز نہ جیت پانے پر قومی ٹیم ...
4,2023-04-25,آئرلینڈ نے ٹیسٹ کرکٹ میں اپنا سب سے زیادہ ٹیس...,گال(اُردو پوائنٹ اخبارتازہ ترین - آن لائن۔ 25 ...,Sports,https://www.urdupoint.com/sports/detail-news/l...,سری لنکا اور آئرلینڈ کے درمیان جاری دو ٹیسٹ...

## Preprocessing of Data
Data was cleaned that saved into column "Clean_Data" we  removed some extra coloumns first like date,Title,Link and some other columns too. Because we do experiment only news  and all other things are extra for us.

Stopwords are common words that are often filtered out during text processing in natural language processing (NLP) tasks. These words are considered to have little or no value in conveying the actual meaning of the text. We take list of 401 stopwords for topic modelling.

In [ ]:
df=df.drop(columns=['Date','Title', 'Link'])

KeyError: ignored

In [ ]:
def remove_nonbreaking_space(text):
    return re.sub(r'\xa0', ' ', text)

df['Clean_Data'] = df['Clean_Data'].apply(remove_nonbreaking_space)

In [ ]:
df

,News,Category,Clean_Data
0,ممبئی(اُردو پوائنٹ اخبارتازہ ترین - آن لائن۔ 2...,Sports,بھارتی کرکٹ کے آئیکون ویرات کوہلی اور انکی ...
1,راولپنڈی(اُردو پوائنٹ اخبارتازہ ترین - آن لائن...,Sports,پاکستان کرکٹ ٹیم کے کپتان بابر اعظم کا کہنا ...
2,نئی دہلی (اُردو پوائنٹ اخبارتازہ ترین - آن لائ...,Sports,رائل چیلنجرز بنگلور کے کپتان ویرات کوہلی کو ا...
3,راولپنڈی (اُردو پوائنٹ اخبارتازہ ترین - آن لائ...,Sports,نیوزی لینڈ سے سیریز نہ جیت پانے پر قومی ٹیم ...
4,گال(اُردو پوائنٹ اخبارتازہ ترین - آن لائن۔ 25 ...,Sports,سری لنکا اور آئرلینڈ کے درمیان جاری دو ٹیسٹ...
...,...,...,...
7986,پشاور(اُردو پوائنٹ اخبارتازہ ترین - اے پی پی۔ ...,Health,پشاور کے لیڈی ریڈنگ ہسپتال میں کورونا وائرس ...
7987,بیروت (اُردو پوائنٹ اخبارتازہ ترین - این این آ...,Health,لبنان کی وزارت صحت نے کووِڈکی اومیکرون قسم کے...
7988,نیویارک(اُردو پوائنٹ اخبارتازہ ترین - این این ...,Health,عالمی ادارہ صحت کے ویکسین ایڈوائزری پینل نے ص...
7989,بھکر۔(اُردو پوائنٹ اخبارتازہ ترین - اے پی پی۔ ...,Health,ڈپٹی کمشنر حامد محمود ملہی کے زیر صدارت ضلعی...
7990,بھکر(اُردو پوائنٹ اخبارتازہ ترین - اے پی پی۔ 0...,Health,وزیر اعلی پنجاب کی خصوصی ہدایات پر کورونا سے ...

In [ ]:
documents = df['Clean_Data'].values.tolist()
print((documents[1]))

  پاکستان کرکٹ ٹیم کے کپتان بابر اعظم کا کہنا ہے کہ شکست کا ملبہ کسی پر بھی نہیں ڈالوں گا کیونکہ یہ ٹیم ورک ہوتا ہے اور ہمیشہ ایک ٹیم جیتتی ہے یا ہارتی ہے تاہم جہاں ضرورت ہے اچھا کرنے کی مزید بہتری ضرور لائیں گے۔راولپنڈی میں ٹی  میچز کی سیریز مکمل ہونے کے بعد پاکستان ٹیم کے کپتان بابر اعظم کا کہنا تھا کہ شروع میں اندازہ تھا کہ  سکور کریں گے لیکن  رنز کا اچھا سکور کیا لیکن نیوزی لینڈ کے کھلاڑی اچھا کھیلے۔ میں کبھی مطمئن نہیں ہوتا اور تربیت بھی یہی ہے کہ اچھا کرکے بھی سیکھا جاتا ہے کیونکہ بری پرفارمنس کے بعد تو ہر کوئی سیکھتا ہے۔بابر اعظم کا کہنا تھا کہ دو دن کے وقفے سے کوئی فرق نہیں پڑتا  اوور کے بعد  کا ہدف سمجھ رہے تھے لیکن یہ درست ہے کہ آخری تین اوور میں رضوان سے ہٹ نہیں لگی رضوان مزید دو رنز کر سکتے تھے لیکن نہیں کرسکے بہرحال رضوان نے بہت اچھا کھیلا کیچز ڈراپ ہوئے جو کہ نہیں ہونے چاہیے تھے۔

In [ ]:
import nltk
stopwords=pd.read_csv('/content/drive/MyDrive/stopwords.txt',names=['List'])
# stopwords['List']

stopwords_ur=[]
for li in stopwords['List']:
  stopwords_ur.append(li)
print(len(stopwords_ur))
print(stopwords_ur)

401
['کی', 'ہیں', 'ہے', 'رہا', 'رہی', 'رہے', 'تھا', 'تھے', 'تھی', 'تھى', 'میں', 'کہ', 'کے', 'ہوتے', 'کہہ', 'بنانا', 'پھر', 'لکین', 'ہوتی', 'لیتی', 'ایسی', 'ائے', 'ہوئے', 'ہوۓ ', 'مگر', 'چاہے', 'کیے', 'تاکہ', 'تم', 'آکر', 'لگا', 'ہوگیئں', 'ليے', 'رہتی', 'ہوگئی', 'انھوں', 'چاہتے', 'پاگیئں', 'آنا', 'کروا', 'رکھ', 'آتی', 'یہاں', 'جیسا', 'چکے', 'کرئے', 'دیے', 'چکا', 'ملتا', 'کبھی', 'ایسا', 'کرسکیں', 'ہوسکے', 'سکیں', 'لہذا', 'چاہئے', 'وہیں', 'اٹھایا', 'جہنوں', 'ہمارے', 'لیے', 'آرہے', 'کرگیئں', 'بنانے', 'سکتا', 'وغیرہ', 'دے', 'ہوۓ', 'رہنے', 'ہوۓ', 'کئے', 'لگے', 'لگایا', 'لائے', 'کہے', 'کرے', 'رہئں', 'آگئے', 'کئی', 'کم', 'ملی', 'جنہیں', 'ہوئیں', 'تھیں', 'ابھی', 'پاگئیں', 'آئے', 'کرا', 'دیا', 'جہاں', 'آگئیں', 'کرتی', 'رہیں', 'کرتیں', 'دیتی', 'ہوگئے', 'ديتے', 'انہں', 'ایسے', 'رکھتے', 'رہتے', 'رکھی', 'کیں', 'كیا', 'وه', 'جنہيں', 'کروائی', 'دینا', 'جسے', 'جاتی', 'اسکی', 'ملے', 'کرگئى', 'جن', 'آپکو', 'جنہوں', 'دیئے', 'والی', 'جبکہ', 'دیگر', 'آپکا', 'رکھنے', 'انہىں', 'کيے', 'یعنی', 'كيے', 'بننے', 'جاملے', 'ليكن', 'كرنے', 'كر', 'آيا', 'كرگئى', 'پھر', 'کچھ', 'آتے', 'دینے', 'اپ', 'ہونا', 'انہیں', 'لگی', 'آنے', 'کرلی', 'ہوگئى', 'پایا', 'آپکے', 'بنائی', 'کرديا', 'لا', 'رکهنے', 'كہ', 'بنا', 'كرديا', 'ركھى', 'ميں', 'ركھتے', 'كروائى', 'حتی', 'لایا', 'لیتے', 'ہمیں', 'گئى', 'بنائے', 'تاہم', 'پھر بھی', 'بنايا', 'دىے', 'ايم اے او', 'كئى', 'پڑا', 'رکھے', 'انہی', 'دیں', 'ليکر', 'البتہ', 'ہى', 'کرکے', 'پائی', 'لینا', 'دہی', 'دئیے', 'گوکہ', 'دئيے', 'كيں', 'جایا', 'کروایا', 'كیے', 'ہاں', 'کہنا', 'کیلئے', 'ہوگا', 'دیکھتے', 'آرہے', 'آگیا', 'اپنے آپ', 'طرف سے', 'ملا', 'آپكى', 'پھر بھی', 'كرگئے', 'آپکی', 'ليا', 'ديے', 'كے', 'رکھى', 'رکھتا', 'کرايا', 'چلے', 'آتا', 'لاکر', 'جیسے', 'کرليا', 'کیا ہے', 'وہاں', 'لینے', 'پاگئے', 'ہر', 'رکھنا', 'كيا', 'آیا', 'هے', 'كى', 'کرایا', 'حاصل', 'آگئى', 'دى', 'کبهی', 'جاسكتا', 'اسى', 'كی', 'كہا', 'كرو', 'اور', 'سے', 'کا', 'کى', 'سب', 'کو', 'كو', 'نے', 'اس', 'ہيں', 'پر', 'کر', 'ايک', 'كا', 'ہو', 'بهی', 'ایک', 'یہ', 'نہيں', 'ان', 'کيا', 'تو', 'وہ', 'لئے', 'کرنے', 'آپ', 'کہا', 'گيا', 'جو', 'گا', 'ہی', 'جائے', 'نہ', 'جب', 'اپنے', 'جس', 'دیا', 'ہوئے', 'تک', 'بعد', 'انہوں', 'رہے', 'ليکن', 'گی', 'کریں', 'گے', 'کرتے', 'ہونے', 'گئے', 'اپنی', 'والے', 'بہت', 'کسی', 'جا', 'تهی', 'یا', 'گئی', 'ہم', 'ہوں', 'کيلئے', 'زیادہ', 'رہا', 'طرح', 'اگر', 'اب', 'ہوا', 'دی', 'ہوتا', 'کام', 'جب', 'جو', 'گا', 'لیکن ', 'کرتى ', 'کرگئی ', 'گیا ', 'اسی', 'کیا', 'ہوئی', 'انہيں', 'جانا', 'جانے ', 'ہوئی ', 'کرگئے ', 'دیا', 'کو ', 'میں', 'ہوئے', 'ایک', 'تھے ', 'آپ ', 'نہیں', 'لیکن', 'تھی', 'جو', 'اور', 'کرتى', 'کرتا', 'کرگئی', 'کر', 'جاتے', 'لئے', 'گیا', 'کہا ', 'جاتا', 'اس ', 'جاتى', 'کرنا', 'کسی', 'بھی', 'طرف', 'ہوتا', 'لیکن', 'یہ', 'ہی', 'یا', 'اگرچہ', 'کہ', 'نے', 'رکھو', 'کرو', 'جانے', 'انہيں ', 'ديا', 'سے', 'کرگئے', 'پر', 'ہوئى', 'ان', 'اپنى', 'اپنا', 'ذریعے', 'رکھا', 'ہونے', 'اپنے', 'بعد', 'پاگئى', 'دیتے', 'كرتے', 'ہوتى', 'کہتے', 'دی', 'کرگئیں', 'اسے', 'اسی', 'لیا', 'لے', 'لی', 'کس', 'کسی', 'لیے', 'آئی', 'بنے', 'کچھ ', 'ہی', 'کرتی', 'کرتا', 'لئے', 'طور', 'نہیں', 'بلکہ', 'کیونکہ', 'کیوں', 'جس ', 'گئی', 'ہونے', 'وجہ', 'ہوگیا', 'لينے']

# BERTopic Training
The default  bertopic embedding model is paraphrase-multilingual-MiniLM-L12-v2 when selecting language="multilingual". we also performed experiment on 2 another pretained multilingual model from [sentence-tranformer](https://www.sbert.net/docs/pretrained_models.html) and create custom document embedding and passed it to the bertopic model for training.

In [ ]:
#create custom embedding
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2')
embeddings = model.encode(documents, show_progress_bar=True)
print(embeddings)

.gitattributes:   0%|          | 0.00/968 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/4.09k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/645 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/471M [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.08M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/480 [00:00<?, ?B/s]

unigram.json:   0%|          | 0.00/14.8M [00:00<?, ?B/s]

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

Batches:   0%|          | 0/250 [00:00<?, ?it/s]

[[ 0.07987808 -0.07742516 -0.08378563 ... -0.043457   -0.11484845
  -0.07181289]
 [ 0.09646066 -0.04020533 -0.04377843 ...  0.00730114  0.09356619
   0.05510345]
 [ 0.00332669  0.09647436 -0.17899874 ... -0.15398908  0.01223139
  -0.0459842 ]
 ...
 [-0.05227447  0.06783362 -0.2360085  ... -0.18109454 -0.0346763
   0.08866747]
 [ 0.1034833   0.31677362  0.00757494 ...  0.09555458  0.02051694
   0.20520177]
 [-0.09281214  0.19791466 -0.18801452 ... -0.22458135 -0.11964664
   0.11853428]]

In [ ]:
#pass vectorizer_model to bertopic for stopwords removal
from sklearn.feature_extraction.text import CountVectorizer

vectorizer_model = CountVectorizer(stop_words= stopwords_ur)

In [ ]:
#ClassTfidf for top words
from bertopic.vectorizers import ClassTfidfTransformer

ctfidf_model = ClassTfidfTransformer(bm25_weighting=True, reduce_frequent_words=True)

In [ ]:
#UMAP for dimention reduction
from umap import UMAP

In [ ]:
from hdbscan import HDBSCAN

In [ ]:
np.random.seed(42)

**Diversity Score**

In [ ]:
def topic_diversity(topics, topk=10):
    """
    compute the proportion of unique words

    Parameters
    ----------
    topics: a list of lists of words
    topk: top k words on which the topic diversity will be computed
    """
    if topk > len(topics[0]):
        raise Exception('Words in topics are less than '+str(topk))
    else:
        unique_words = set()
        for topic in topics:
            unique_words = unique_words.union(set(topic[:topk]))
        puw = len(unique_words) / (topk * len(topics))
        return puw

In [ ]:
import itertools
from rbo import rbo
import numpy as np

class InvertedRBO:
    def __init__(self):
        pass

    def irbo(self, topics, topk=10, weight=0.9):
        """
        Calculate inverted Rank Biased Overlap (RBO) as a measure of topic diversity from a list of lists of words.

        :param topics: A list of lists of words representing different topics.
        :param topk: The number of top words on which RBO will be computed.
        :param weight: Weight of each agreement at depth d: p**(d-1). When set to 1.0, there is no weight,
                       and the RBO returns to average overlap.
        :return: The inverted RBO topic diversity score.
        """
        if topk <= 0:
            raise ValueError("topk must be a positive integer.")

        num_topics = len(topics)
        if num_topics == 0:
            raise ValueError("topics list cannot be empty.")

        if topk > len(topics[0]):
            raise Exception('Words in topics are less than topk')

        collect = []
        for list1, list2 in itertools.combinations(topics, 2):
            rbo_val = rbo(list1[:topk], list2[:topk], p=weight)[2]
            collect.append(rbo_val)

        Irbo_score = 1 - np.mean(collect)
        return Irbo_score

In [ ]:
import pandas as pd
from sklearn.cluster import KMeans
from itertools import product
from sklearn.cluster import AgglomerativeClustering

# cluster_model = AgglomerativeClustering(n_clusters=7)
# cluster_model = KMeans(n_clusters=7, random_state=42)
texts = [[word for word in str(document).split() if word not in stopwords_ur] for document in documents]
id2word = corpora.Dictionary(texts)
corpus = [id2word.doc2bow(text) for text in texts]

# Define lists for n_neighbors and n_components
n_neighbors_list = [5, 10,15,20,25,30]
n_components_list = [2, 3, 4, 5]

# Create a list to store the data for each combination
data_list = []

# Loop over the parameter combinations and fit BERTopic models
for n_neighbors, n_components in product(n_neighbors_list, n_components_list):
    umap_param = {'n_neighbors': n_neighbors, 'n_components': n_components}

    # Create UMAP and HDBSCAN models with the current parameter combination
    umap_model = UMAP(**umap_param, random_state=42)

    # Fit a BERTopic model with the current parameter combination
    topic_model = BERTopic(language="urdu",
                          low_memory=True,
                          calculate_probabilities=True,
                          vectorizer_model=vectorizer_model,
                          top_n_words=10,
                          ctfidf_model=ctfidf_model,
                          verbose=True, umap_model=umap_model, nr_topics=8)

    topics, probs = topic_model.fit_transform(documents, embeddings)

    topics_bert = []
    for i in topic_model.get_topics():
        row = []
        topic = topic_model.get_topic(i)
        for word in topic:
            row.append(word[0])
        topics_bert.append(row)

    # Calculate coherence scores using Gensim's Coherence Model
    coherence_cv = CoherenceModel(topics=topics_bert, texts=texts, dictionary=id2word, coherence='c_v')
    cv_score = round(coherence_cv.get_coherence(),3)
    coherence_npmi = CoherenceModel(topics=topics_bert, texts=texts, dictionary=id2word, coherence='c_npmi')
    npmi_score = round(coherence_npmi.get_coherence(),3)

    # Calculate Unique Word count
    unique_words = round(topic_diversity(topics_bert, topk=10),3)

    # Calculate IRBO Score
    inverted_rbo_calculator = InvertedRBO()
    IRBO = round(inverted_rbo_calculator.irbo(topics_bert, topk=10, weight=0.9),3)

    # Append the data for the current combination to the list
    data_list.append({
        'Clustering': 'HDBSCAN',
        'Pretrained_Model': 'MiniLM',
        'n_neighbors': n_neighbors,
        'n_components': n_components,
        'C_v score': cv_score,
        'C_NPMI score': npmi_score,
        'Unique Word': unique_words,
        'IRBO Score': IRBO,
        'Topics': topics_bert
    })

# Create a DataFrame from the data list
df1 = pd.DataFrame(data_list)

# Print the DataFrame
print(df1)

2023-11-29 17:02:31,267 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2023-11-29 17:02:42,293 - BERTopic - Dimensionality - Completed ✓
2023-11-29 17:02:42,299 - BERTopic - Cluster - Start clustering the reduced embeddings
2023-11-29 17:02:52,001 - BERTopic - Cluster - Completed ✓
2023-11-29 17:02:52,003 - BERTopic - Representation - Extracting topics from clusters using representation models.
2023-11-29 17:02:56,471 - BERTopic - Representation - Completed ✓
2023-11-29 17:02:56,476 - BERTopic - Topic reduction - Reducing number of topics
2023-11-29 17:03:02,610 - BERTopic - Topic reduction - Reduced number of topics from 137 to 8
2023-11-29 17:03:23,929 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2023-11-29 17:03:36,544 - BERTopic - Dimensionality - Completed ✓
2023-11-29 17:03:36,547 - BERTopic - Cluster - Start clustering the reduced embeddings
2023-11-29 17:03:43,778 - BERTopic - Cluster - Completed ✓
2023-11-29 17:03:43,780 - BERTopic - Representation - Extracting topics from clusters using representation models.
2023-11-29 17:03:50,246 - BERTopic - Representation - Completed ✓
2023-11-29 17:03:50,251 - BERTopic - Topic reduction - Reducing number of topics
2023-11-29 17:03:55,264 - BERTopic - Topic reduction - Reduced number of topics from 131 to 8
2023-11-29 17:04:15,445 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2023-11-29 17:04:28,417 - BERTopic - Dimensionality - Completed ✓
2023-11-29 17:04:28,419 - BERTopic - Cluster - Start clustering the reduced embeddings
2023-11-29 17:04:35,908 - BERTopic - Cluster - Completed ✓
2023-11-29 17:04:35,910 - BERTopic - Representation - Extracting topics from clusters using representation models.
2023-11-29 17:04:41,135 - BERTopic - Representation - Completed ✓
2023-11-29 17:04:41,144 - BERTopic - Topic reduction - Reducing number of topics
2023-11-29 17:04:46,153 - BERTopic - Topic reduction - Reduced number of topics from 141 to 8
2023-11-29 17:05:07,353 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2023-11-29 17:05:20,877 - BERTopic - Dimensionality - Completed ✓
2023-11-29 17:05:20,879 - BERTopic - Cluster - Start clustering the reduced embeddings
2023-11-29 17:05:29,315 - BERTopic - Cluster - Completed ✓
2023-11-29 17:05:29,322 - BERTopic - Representation - Extracting topics from clusters using representation models.
2023-11-29 17:05:35,770 - BERTopic - Representation - Completed ✓
2023-11-29 17:05:35,774 - BERTopic - Topic reduction - Reducing number of topics
2023-11-29 17:05:39,353 - BERTopic - Topic reduction - Reduced number of topics from 140 to 8
2023-11-29 17:06:00,035 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2023-11-29 17:06:16,136 - BERTopic - Dimensionality - Completed ✓
2023-11-29 17:06:16,138 - BERTopic - Cluster - Start clustering the reduced embeddings
2023-11-29 17:06:23,298 - BERTopic - Cluster - Completed ✓
2023-11-29 17:06:23,305 - BERTopic - Representation - Extracting topics from clusters using representation models.
2023-11-29 17:06:28,719 - BERTopic - Representation - Completed ✓
2023-11-29 17:06:28,724 - BERTopic - Topic reduction - Reducing number of topics
2023-11-29 17:06:32,404 - BERTopic - Topic reduction - Reduced number of topics from 116 to 8
2023-11-29 17:06:54,128 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2023-11-29 17:07:11,642 - BERTopic - Dimensionality - Completed ✓
2023-11-29 17:07:11,647 - BERTopic - Cluster - Start clustering the reduced embeddings
2023-11-29 17:07:18,950 - BERTopic - Cluster - Completed ✓
2023-11-29 17:07:18,953 - BERTopic - Representation - Extracting topics from clusters using representation models.
2023-11-29 17:07:22,746 - BERTopic - Representation - Completed ✓
2023-11-29 17:07:22,753 - BERTopic - Topic reduction - Reducing number of topics
2023-11-29 17:07:26,425 - BERTopic - Topic reduction - Reduced number of topics from 107 to 8
2023-11-29 17:07:48,401 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2023-11-29 17:08:08,019 - BERTopic - Dimensionality - Completed ✓
2023-11-29 17:08:08,023 - BERTopic - Cluster - Start clustering the reduced embeddings
2023-11-29 17:08:13,248 - BERTopic - Cluster - Completed ✓
2023-11-29 17:08:13,254 - BERTopic - Representation - Extracting topics from clusters using representation models.
2023-11-29 17:08:17,211 - BERTopic - Representation - Completed ✓
2023-11-29 17:08:17,215 - BERTopic - Topic reduction - Reducing number of topics
2023-11-29 17:08:21,754 - BERTopic - Topic reduction - Reduced number of topics from 98 to 8
2023-11-29 17:08:44,478 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2023-11-29 17:09:03,040 - BERTopic - Dimensionality - Completed ✓
2023-11-29 17:09:03,042 - BERTopic - Cluster - Start clustering the reduced embeddings
2023-11-29 17:09:07,261 - BERTopic - Cluster - Completed ✓
2023-11-29 17:09:07,263 - BERTopic - Representation - Extracting topics from clusters using representation models.
2023-11-29 17:09:11,510 - BERTopic - Representation - Completed ✓
2023-11-29 17:09:11,519 - BERTopic - Topic reduction - Reducing number of topics
2023-11-29 17:09:17,748 - BERTopic - Topic reduction - Reduced number of topics from 94 to 8
2023-11-29 17:09:38,793 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2023-11-29 17:09:57,574 - BERTopic - Dimensionality - Completed ✓
2023-11-29 17:09:57,577 - BERTopic - Cluster - Start clustering the reduced embeddings
2023-11-29 17:10:01,649 - BERTopic - Cluster - Completed ✓
2023-11-29 17:10:01,651 - BERTopic - Representation - Extracting topics from clusters using representation models.
2023-11-29 17:10:08,193 - BERTopic - Representation - Completed ✓
2023-11-29 17:10:08,197 - BERTopic - Topic reduction - Reducing number of topics
2023-11-29 17:10:11,995 - BERTopic - Topic reduction - Reduced number of topics from 95 to 8
2023-11-29 17:10:32,497 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2023-11-29 17:10:52,085 - BERTopic - Dimensionality - Completed ✓
2023-11-29 17:10:52,089 - BERTopic - Cluster - Start clustering the reduced embeddings
2023-11-29 17:10:58,146 - BERTopic - Cluster - Completed ✓
2023-11-29 17:10:58,154 - BERTopic - Representation - Extracting topics from clusters using representation models.
2023-11-29 17:11:02,570 - BERTopic - Representation - Completed ✓
2023-11-29 17:11:02,573 - BERTopic - Topic reduction - Reducing number of topics
2023-11-29 17:11:06,197 - BERTopic - Topic reduction - Reduced number of topics from 82 to 8
2023-11-29 17:11:27,151 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2023-11-29 17:11:51,083 - BERTopic - Dimensionality - Completed ✓
2023-11-29 17:11:51,089 - BERTopic - Cluster - Start clustering the reduced embeddings
2023-11-29 17:11:54,579 - BERTopic - Cluster - Completed ✓
2023-11-29 17:11:54,580 - BERTopic - Representation - Extracting topics from clusters using representation models.
2023-11-29 17:11:58,294 - BERTopic - Representation - Completed ✓
2023-11-29 17:11:58,299 - BERTopic - Topic reduction - Reducing number of topics
2023-11-29 17:12:02,232 - BERTopic - Topic reduction - Reduced number of topics from 81 to 8
2023-11-29 17:12:24,461 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2023-11-29 17:12:46,153 - BERTopic - Dimensionality - Completed ✓
2023-11-29 17:12:46,155 - BERTopic - Cluster - Start clustering the reduced embeddings
2023-11-29 17:12:49,660 - BERTopic - Cluster - Completed ✓
2023-11-29 17:12:49,662 - BERTopic - Representation - Extracting topics from clusters using representation models.
2023-11-29 17:12:54,222 - BERTopic - Representation - Completed ✓
2023-11-29 17:12:54,230 - BERTopic - Topic reduction - Reducing number of topics
2023-11-29 17:13:00,151 - BERTopic - Topic reduction - Reduced number of topics from 81 to 8
2023-11-29 17:13:20,279 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2023-11-29 17:13:41,287 - BERTopic - Dimensionality - Completed ✓
2023-11-29 17:13:41,290 - BERTopic - Cluster - Start clustering the reduced embeddings
2023-11-29 17:13:46,406 - BERTopic - Cluster - Completed ✓
2023-11-29 17:13:46,413 - BERTopic - Representation - Extracting topics from clusters using representation models.
2023-11-29 17:13:51,867 - BERTopic - Representation - Completed ✓
2023-11-29 17:13:51,871 - BERTopic - Topic reduction - Reducing number of topics
2023-11-29 17:13:55,472 - BERTopic - Topic reduction - Reduced number of topics from 78 to 8
2023-11-29 17:14:15,930 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2023-11-29 17:14:39,213 - BERTopic - Dimensionality - Completed ✓
2023-11-29 17:14:39,216 - BERTopic - Cluster - Start clustering the reduced embeddings
2023-11-29 17:14:43,292 - BERTopic - Cluster - Completed ✓
2023-11-29 17:14:43,295 - BERTopic - Representation - Extracting topics from clusters using representation models.
2023-11-29 17:14:47,067 - BERTopic - Representation - Completed ✓
2023-11-29 17:14:47,070 - BERTopic - Topic reduction - Reducing number of topics
2023-11-29 17:14:50,749 - BERTopic - Topic reduction - Reduced number of topics from 76 to 8
2023-11-29 17:15:13,488 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2023-11-29 17:15:37,553 - BERTopic - Dimensionality - Completed ✓
2023-11-29 17:15:37,555 - BERTopic - Cluster - Start clustering the reduced embeddings
2023-11-29 17:15:40,299 - BERTopic - Cluster - Completed ✓
2023-11-29 17:15:40,301 - BERTopic - Representation - Extracting topics from clusters using representation models.
2023-11-29 17:15:44,379 - BERTopic - Representation - Completed ✓
2023-11-29 17:15:44,386 - BERTopic - Topic reduction - Reducing number of topics
2023-11-29 17:15:51,015 - BERTopic - Topic reduction - Reduced number of topics from 64 to 8
2023-11-29 17:16:13,353 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2023-11-29 17:16:41,791 - BERTopic - Dimensionality - Completed ✓
2023-11-29 17:16:41,798 - BERTopic - Cluster - Start clustering the reduced embeddings
2023-11-29 17:16:45,261 - BERTopic - Cluster - Completed ✓
2023-11-29 17:16:45,263 - BERTopic - Representation - Extracting topics from clusters using representation models.
2023-11-29 17:16:49,382 - BERTopic - Representation - Completed ✓
2023-11-29 17:16:49,388 - BERTopic - Topic reduction - Reducing number of topics
2023-11-29 17:16:53,425 - BERTopic - Topic reduction - Reduced number of topics from 64 to 8
2023-11-29 17:17:19,785 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2023-11-29 17:17:43,200 - BERTopic - Dimensionality - Completed ✓
2023-11-29 17:17:43,202 - BERTopic - Cluster - Start clustering the reduced embeddings
2023-11-29 17:17:47,105 - BERTopic - Cluster - Completed ✓
2023-11-29 17:17:47,113 - BERTopic - Representation - Extracting topics from clusters using representation models.
2023-11-29 17:17:53,030 - BERTopic - Representation - Completed ✓
2023-11-29 17:17:53,034 - BERTopic - Topic reduction - Reducing number of topics
2023-11-29 17:17:56,701 - BERTopic - Topic reduction - Reduced number of topics from 82 to 8
2023-11-29 17:18:17,304 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2023-11-29 17:18:43,248 - BERTopic - Dimensionality - Completed ✓
2023-11-29 17:18:43,256 - BERTopic - Cluster - Start clustering the reduced embeddings
2023-11-29 17:18:46,363 - BERTopic - Cluster - Completed ✓
2023-11-29 17:18:46,367 - BERTopic - Representation - Extracting topics from clusters using representation models.
2023-11-29 17:18:50,193 - BERTopic - Representation - Completed ✓
2023-11-29 17:18:50,198 - BERTopic - Topic reduction - Reducing number of topics
2023-11-29 17:18:54,307 - BERTopic - Topic reduction - Reduced number of topics from 73 to 8
2023-11-29 17:19:17,705 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2023-11-29 17:19:42,544 - BERTopic - Dimensionality - Completed ✓
2023-11-29 17:19:42,547 - BERTopic - Cluster - Start clustering the reduced embeddings
2023-11-29 17:19:46,477 - BERTopic - Cluster - Completed ✓
2023-11-29 17:19:46,484 - BERTopic - Representation - Extracting topics from clusters using representation models.
2023-11-29 17:19:52,318 - BERTopic - Representation - Completed ✓
2023-11-29 17:19:52,323 - BERTopic - Topic reduction - Reducing number of topics
2023-11-29 17:19:56,035 - BERTopic - Topic reduction - Reduced number of topics from 69 to 8
2023-11-29 17:20:16,909 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2023-11-29 17:20:45,082 - BERTopic - Dimensionality - Completed ✓
2023-11-29 17:20:45,087 - BERTopic - Cluster - Start clustering the reduced embeddings
2023-11-29 17:20:47,590 - BERTopic - Cluster - Completed ✓
2023-11-29 17:20:47,593 - BERTopic - Representation - Extracting topics from clusters using representation models.
2023-11-29 17:20:51,300 - BERTopic - Representation - Completed ✓
2023-11-29 17:20:51,304 - BERTopic - Topic reduction - Reducing number of topics
2023-11-29 17:20:56,678 - BERTopic - Topic reduction - Reduced number of topics from 60 to 8
2023-11-29 17:21:18,307 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2023-11-29 17:21:42,326 - BERTopic - Dimensionality - Completed ✓
2023-11-29 17:21:42,329 - BERTopic - Cluster - Start clustering the reduced embeddings
2023-11-29 17:21:47,791 - BERTopic - Cluster - Completed ✓
2023-11-29 17:21:47,798 - BERTopic - Representation - Extracting topics from clusters using representation models.
2023-11-29 17:21:52,611 - BERTopic - Representation - Completed ✓
2023-11-29 17:21:52,617 - BERTopic - Topic reduction - Reducing number of topics
2023-11-29 17:21:56,195 - BERTopic - Topic reduction - Reduced number of topics from 76 to 8
2023-11-29 17:22:17,226 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2023-11-29 17:22:45,408 - BERTopic - Dimensionality - Completed ✓
2023-11-29 17:22:45,410 - BERTopic - Cluster - Start clustering the reduced embeddings
2023-11-29 17:22:47,881 - BERTopic - Cluster - Completed ✓
2023-11-29 17:22:47,883 - BERTopic - Representation - Extracting topics from clusters using representation models.
2023-11-29 17:22:51,586 - BERTopic - Representation - Completed ✓
2023-11-29 17:22:51,590 - BERTopic - Topic reduction - Reducing number of topics
2023-11-29 17:22:57,525 - BERTopic - Topic reduction - Reduced number of topics from 64 to 8
2023-11-29 17:23:18,823 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2023-11-29 17:23:45,938 - BERTopic - Dimensionality - Completed ✓
2023-11-29 17:23:45,943 - BERTopic - Cluster - Start clustering the reduced embeddings
2023-11-29 17:23:50,082 - BERTopic - Cluster - Completed ✓
2023-11-29 17:23:50,085 - BERTopic - Representation - Extracting topics from clusters using representation models.
2023-11-29 17:23:53,831 - BERTopic - Representation - Completed ✓
2023-11-29 17:23:53,836 - BERTopic - Topic reduction - Reducing number of topics
2023-11-29 17:23:57,440 - BERTopic - Topic reduction - Reduced number of topics from 63 to 8
2023-11-29 17:24:18,856 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2023-11-29 17:24:49,830 - BERTopic - Dimensionality - Completed ✓
2023-11-29 17:24:49,832 - BERTopic - Cluster - Start clustering the reduced embeddings
2023-11-29 17:24:52,336 - BERTopic - Cluster - Completed ✓
2023-11-29 17:24:52,343 - BERTopic - Representation - Extracting topics from clusters using representation models.
2023-11-29 17:24:59,497 - BERTopic - Representation - Completed ✓
2023-11-29 17:24:59,501 - BERTopic - Topic reduction - Reducing number of topics
2023-11-29 17:25:03,172 - BERTopic - Topic reduction - Reduced number of topics from 55 to 8

   Clustering Pretrained_Model  n_neighbors  n_components  C_v score  \
0     HDBSCAN           MiniLM            5             2      0.625
1     HDBSCAN           MiniLM            5             3      0.601
2     HDBSCAN           MiniLM            5             4      0.672
3     HDBSCAN           MiniLM            5             5      0.670
4     HDBSCAN           MiniLM           10             2      0.641
5     HDBSCAN           MiniLM           10             3      0.645
6     HDBSCAN           MiniLM           10             4      0.682
7     HDBSCAN           MiniLM           10             5      0.607
8     HDBSCAN           MiniLM           15             2      0.632
9     HDBSCAN           MiniLM           15             3      0.684
10    HDBSCAN           MiniLM           15             4      0.598
11    HDBSCAN           MiniLM           15             5      0.667
12    HDBSCAN           MiniLM           20             2      0.634
13    HDBSCAN           MiniLM           20             3      0.653
14    HDBSCAN           MiniLM           20             4      0.602
15    HDBSCAN           MiniLM           20             5      0.622
16    HDBSCAN           MiniLM           25             2      0.594
17    HDBSCAN           MiniLM           25             3      0.584
18    HDBSCAN           MiniLM           25             4      0.653
19    HDBSCAN           MiniLM           25             5      0.634
20    HDBSCAN           MiniLM           30             2      0.711
21    HDBSCAN           MiniLM           30             3      0.594
22    HDBSCAN           MiniLM           30             4      0.625
23    HDBSCAN           MiniLM           30             5      0.658

    C_NPMI score  Unique Word  IRBO Score  \
0          0.129        0.887       0.978
1          0.121        0.925       0.987
2          0.154        0.912       0.986
3          0.167        0.900       0.980
4          0.126        0.938       0.989
5          0.130        0.950       0.992
6          0.157        0.925       0.987
7          0.109        0.950       0.991
8          0.122        0.912       0.982
9          0.162        0.912       0.987
10         0.107        0.925       0.981
11         0.139        0.912       0.985
12         0.163        0.887       0.970
13         0.136        0.912       0.988
14         0.103        0.900       0.983
15         0.116        0.938       0.990
16         0.103        0.912       0.982
17         0.111        0.938       0.991
18         0.142        0.938       0.991
19         0.128        0.925       0.987
20         0.166        0.925       0.990
21         0.090        0.938       0.991
22         0.118        0.900       0.981
23         0.140        0.938       0.992

                                               Topics
0   [[پاکستان, مطابق, سی, سال, ساتھ, صحت, بتایا, پ...
1   [[پاکستان, سی, مطابق, صحت, ساتھ, بتایا, سال, ک...
2   [[پاکستان, سی, ساتھ, مطابق, بتایا, سال, صحت, م...
3   [[سی, مطابق, پاکستان, بتایا, ساتھ, سال, روپے, ...
4   [[ساتھ, پاکستان, سال, مطابق, بتایا, صارفین, می...
5   [[پاکستان, سی, ساتھ, مطابق, سال, فیصد, بتایا, ...
6   [[سی, پاکستان, ساتھ, سال, کورونا, مطابق, روپے,...
7   [[ساتھ, سال, پاکستان, سی, مطابق, صحت, کورونا, ...
8   [[پاکستان, سی, کورونا, مطابق, ساتھ, بتایا, سال...
9   [[سی, پاکستان, صحت, سال, مطابق, ساتھ, کورونا, ...
10  [[کورونا, پاکستان, سی, مطابق, ساتھ, صحت, سال, ...
11  [[پاکستان, مطابق, ساتھ, سی, بتایا, سال, صحت, ا...
12  [[کورونا, سی, مطابق, صحت, سال, پاکستان, صارفین...
13  [[پاکستان, سی, مطابق, سال, استعمال, ساتھ, بتای...
14  [[سی, پاکستان, مطابق, استعمال, سال, بتایا, سات...
15  [[سی, مطابق, سال, استعمال, پاکستان, صحت, بتایا...
16  [[سی, پاکستان, صارفین, ساتھ, سال, کورونا, استع...
17  [[سی, پاکستان, مطابق, ٹی, پی, ساتھ, بتایا, سال...
18  [[سی, پاکستان, ساتھ, مطابق, ٹی, سال, بتایا, پی...
19  [[سی, پاکستان, سال, مطابق, استعمال, صحت, بتایا...
20  [[سی, مطابق, پاکستان, صحت, بتایا, ساتھ, سال, ا...
21  [[سی, پاکستان, مطابق, ٹی, سال, ساتھ, صحت, پی, ...
22  [[سی, مطابق, بتایا, ساتھ, سال, پاکستان, استعما...
23  [[سی, پاکستان, پی, مطابق, ٹی, استعمال, صحت, سا...

In [ ]:
# Save the DataFrame to a CSV file
df1.to_csv('UNTM_HDBSCAN_ClusteringF.csv', mode='a', index=False,  encoding='utf-8-sig')