#BERTopic on UDC Sample Dataset
In this notebook I have implemented Topic Modeling on Urdu News Data using a transformer based topic modeling technique BERTopic.

## Mounting Google Drive
If the dataset is on Google Drive then you have to mount over google drive with collaboratory.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive



#Installing required dependencies
**One thing to remember is that after installing libraries you have to restart the run time again so that other dependencies are not affected by it.**

In [ ]:
!pip install bertopic

Collecting bertopic
  Downloading bertopic-0.16.0-py2.py3-none-any.whl (154 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.1/154.1 kB 1.8 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.10/dist-packages (from bertopic) (1.23.5)
Collecting hdbscan>=0.8.29 (from bertopic)
  Downloading hdbscan-0.8.33.tar.gz (5.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 19.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting umap-learn>=0.5.0 (from bertopic)
  Downloading umap-learn-0.5.5.tar.gz (90 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.9/90.9 kB 10.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pandas>=1.1.5 in /usr/local/lib/python3.10/dist-packages (from bertopic) (1.5.3)
Requirement already satisfied: scikit-learn>=0.22.2.post1 in /usr/local/lib/python3.10/dist-packages (from bertopic) (1.2.2)
Requirement already satisfied: tqdm>=4.41.1 in /usr/local/lib/python3.10/dist-packages (from bertopic) (4.66.1)
Collecting sentence-transformers>=0.4.1 (from bertopic)
  Downloading sentence_transformers-2.3.1-py3-none-any.whl (132 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.8/132.8 kB 15.0 MB/s eta 0:00:00
Requirement already satisfied: plotly>=4.7.0 in /usr/local/lib/python3.10/dist-packages (from bertopic) (5.15.0)
Collecting cython<3,>=0.27 (from hdbscan>=0.8.29->bertopic)
  Using cached Cython-0.29.37-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (1.9 MB)
Requirement already satisfied: scipy>=1.0 in /usr/local/lib/python3.10/dist-packages (from hdbscan>=0.8.29->bertopic) (1.11.4)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.10/dist-packages (from hdbscan>=0.8.29->bertopic) (1.3.2)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.1.5->bertopic) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.1.5->bertopic) (2023.4)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from plotly>=4.7.0->bertopic) (8.2.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from plotly>=4.7.0->bertopic) (23.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.22.2.post1->bertopic) (3.2.0)
Requirement already satisfied: transformers<5.0.0,>=4.32.0 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers>=0.4.1->bertopic) (4.35.2)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers>=0.4.1->bertopic) (2.1.0+cu121)
Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (from sentence-transformers>=0.4.1->bertopic) (3.8.1)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.10/dist-packages (from sentence-transformers>=0.4.1->bertopic) (0.1.99)
Requirement already satisfied: huggingface-hub>=0.15.1 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers>=0.4.1->bertopic) (0.20.3)
Requirement already satisfied: Pillow in /usr/local/lib/python3.10/dist-packages (from sentence-transformers>=0.4.1->bertopic) (9.4.0)
Requirement already satisfied: numba>=0.51.2 in /usr/local/lib/python3.10/dist-packages (from umap-learn>=0.5.0->bertopic) (0.58.1)
Collecting pynndescent>=0.5 (from umap-learn>=0.5.0->bertopic)
  Downloading pynndescent-0.5.11-py3-none-any.whl (55 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.8/55.8 kB 7.1 MB/s eta 0:00:00
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.15.1->sentence-transformers>=0.4.1->bertopic) (3.13.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.15.1->sentence-transformers>=0.4.1->bertopic) (2023.6.0)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.15.1->sentence-transformers>=0.4.1->bertopic) (2.31.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.15.1->sentence-transformers>=0.4.1->bertopic) (6.0.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.15.1->sentence-transformers>=0.4.1->bertopic) (4.5.0)
Requirement already satisfied: llvmlite<0.42,>=0.41.0dev0 in /usr/local/lib/python3.10/dist-packages (from numba>=0.51.2->umap-learn>=0.5.0->bertopic) (0.41.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas>=1.1.5->bertopic) (1.16.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.12)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.2.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.1.3)
Requirement already satisfied: triton==2.1.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (2.1.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.32.0->sentence-transformers>=0.4.1->bertopic) (2023.12.25)
Requirement already satisfied: tokenizers<0.19,>=0.14 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.32.0->sentence-transformers>=0.4.1->bertopic) (0.15.1)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.32.0->sentence-transformers>=0.4.1->bertopic) (0.4.2)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk->sentence-transformers>=0.4.1->bertopic) (8.1.7)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (2.1.4)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.15.1->sentence-transformers>=0.4.1->bertopic) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.15.1->sentence-transformers>=0.4.1->bertopic) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.15.1->sentence-transformers>=0.4.1->bertopic) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.15.1->sentence-transformers>=0.4.1->bertopic) (2023.11.17)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.3.0)
Building wheels for collected packages: hdbscan, umap-learn
  Building wheel for hdbscan (pyproject.toml) ... done
  Created wheel for hdbscan: filename=hdbscan-0.8.33-cp310-cp310-linux_x86_64.whl size=3039292 sha256=e6303bb0726573b8a4f911ebeb863784c8e3d33a5dcd03c9fc3d5ef9c8ec59be
  Stored in directory: /root/.cache/pip/wheels/75/0b/3b/dc4f60b7cc455efaefb62883a7483e76f09d06ca81cf87d610
  Building wheel for umap-learn (setup.py) ... done
  Created wheel for umap-learn: filename=umap_learn-0.5.5-py3-none-any.whl size=86832 sha256=c998a734c5199ae6770fc88d9d99d569d73624711d9dafebb71a68a5afff5737
  Stored in directory: /root/.cache/pip/wheels/3a/70/07/428d2b58660a1a3b431db59b806a10da736612ebbc66c1bcc5
Successfully built hdbscan umap-learn
Installing collected packages: cython, pynndescent, hdbscan, umap-learn, sentence-transformers, bertopic
  Attempting uninstall: cython
    Found existing installation: Cython 3.0.8
    Uninstalling Cython-3.0.8:
      Successfully uninstalled Cython-3.0.8
Successfully installed bertopic-0.16.0 cython-0.29.37 hdbscan-0.8.33 pynndescent-0.5.11 sentence-transformers-2.3.1 umap-learn-0.5.5

In [ ]:
!pip install -U sentence-transformers

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.10/dist-packages (2.3.1)
Requirement already satisfied: transformers<5.0.0,>=4.32.0 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (4.35.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (4.66.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (2.1.0+cu121)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (1.23.5)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (1.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (1.11.4)
Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (3.8.1)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (0.1.99)
Requirement already satisfied: huggingface-hub>=0.15.1 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (0.20.3)
Requirement already satisfied: Pillow in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (9.4.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.15.1->sentence-transformers) (3.13.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.15.1->sentence-transformers) (2023.6.0)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.15.1->sentence-transformers) (2.31.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.15.1->sentence-transformers) (6.0.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.15.1->sentence-transformers) (4.5.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.15.1->sentence-transformers) (23.2)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers) (1.12)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers) (3.2.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.3)
Requirement already satisfied: triton==2.1.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers) (2.1.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.32.0->sentence-transformers) (2023.12.25)
Requirement already satisfied: tokenizers<0.19,>=0.14 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.32.0->sentence-transformers) (0.15.1)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.32.0->sentence-transformers) (0.4.2)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk->sentence-transformers) (8.1.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk->sentence-transformers) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->sentence-transformers) (3.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (2.1.4)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.15.1->sentence-transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.15.1->sentence-transformers) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.15.1->sentence-transformers) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.15.1->sentence-transformers) (2023.11.17)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.11.0->sentence-transformers) (1.3.0)

In [ ]:
!pip install --upgrade tensorflow

Requirement already satisfied: tensorflow in /usr/local/lib/python3.10/dist-packages (2.12.0)
Collecting tensorflow
  Downloading tensorflow-2.15.0.post1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (475.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 475.2/475.2 MB 1.4 MB/s eta 0:00:00
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=23.5.26 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (23.5.26)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.4.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: h5py>=2.9.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (3.9.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (16.0.6)
Requirement already satisfied: ml-dtypes~=0.2.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: numpy<2.0.0,>=1.23.5 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.23.5)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from tensorflow) (23.2)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (3.20.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from tensorflow) (67.7.2)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (2.4.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (4.5.0)
Requirement already satisfied: wrapt<1.15,>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.14.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (0.35.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow) (1.60.0)
Collecting tensorboard<2.16,>=2.15 (from tensorflow)
  Downloading tensorboard-2.15.1-py3-none-any.whl (5.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 40.0 MB/s eta 0:00:00
Collecting tensorflow-estimator<2.16,>=2.15.0 (from tensorflow)
  Downloading tensorflow_estimator-2.15.0-py2.py3-none-any.whl (441 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 442.0/442.0 kB 9.9 MB/s eta 0:00:00
Collecting keras<2.16,>=2.15.0 (from tensorflow)
  Downloading keras-2.15.0-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 45.8 MB/s eta 0:00:00
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from astunparse>=1.6.0->tensorflow) (0.42.0)
Requirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow) (2.17.3)
Collecting google-auth-oauthlib<2,>=0.5 (from tensorboard<2.16,>=2.15->tensorflow)
  Downloading google_auth_oauthlib-1.2.0-py2.py3-none-any.whl (24 kB)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow) (3.5.2)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow) (2.31.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.16,>=2.15->tensorflow) (3.0.1)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow) (5.3.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow) (0.3.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow) (1.3.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow) (2023.11.17)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.10/dist-packages (from werkzeug>=1.0.1->tensorboard<2.16,>=2.15->tensorflow) (2.1.4)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /usr/local/lib/python3.10/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow) (0.5.1)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow) (3.2.2)
Installing collected packages: tensorflow-estimator, keras, google-auth-oauthlib, tensorboard, tensorflow
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.12.0
    Uninstalling tensorflow-estimator-2.12.0:
      Successfully uninstalled tensorflow-estimator-2.12.0
  Attempting uninstall: keras
    Found existing installation: keras 2.12.0
    Uninstalling keras-2.12.0:
      Successfully uninstalled keras-2.12.0
  Attempting uninstall: google-auth-oauthlib
    Found existing installation: google-auth-oauthlib 0.4.6
    Uninstalling google-auth-oauthlib-0.4.6:
      Successfully uninstalled google-auth-oauthlib-0.4.6
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.12.0
    Uninstalling tensorboard-2.12.0:
      Successfully uninstalled tensorboard-2.12.0
  Attempting uninstall: tensorflow
    Found existing installation: tensorflow 2.12.0
    Uninstalling tensorflow-2.12.0:
      Successfully uninstalled tensorflow-2.12.0
Successfully installed google-auth-oauthlib-1.2.0 keras-2.15.0 tensorboard-2.15.1 tensorflow-2.15.0.post1 tensorflow-estimator-2.15.0


# Importing required dependencies
We will import numpy, pandas and re, bertopic, gensim library for now. other libraries will be imported in the notebook later.

Pandas will be used to create a Dataframe and handle the csv file. Numpy will be used for the faster computation of arrays to save time. re library will be used for the cleaning of data. gensim library is used to get coherence score. bertopic is used to train bertopic on UDC dataset with using pretrained language models

In [ ]:
import pandas as pd
import numpy as np
import re
from bertopic import BERTopic
from gensim.models.coherencemodel import CoherenceModel
import gensim.corpora as corpora
#optional
import logging
logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.ERROR)

import warnings
warnings.filterwarnings("ignore",category=DeprecationWarning)

##DataFrame

In [ ]:
#load UNTM Dataset
df = pd.read_csv('/content/drive/MyDrive/sampled_UDC.csv', encoding='utf-8')

In [ ]:
print(len(df))
df.head()

101

,Document,Category,Clean_Data
0,بی آئی ایس پی نے بجٹ میں 100 فیصد اضافہ مانگ...,Business,بی آئی ایس پی نے بجٹ میں فیصد اضافہ مانگ لی...
1,پی ایس او کے مختلف اداروں پر واجبات 335 ارب س...,Business,پی ایس او کے مختلف اداروں پر واجبات ارب سے ت...
2,کراچی: تھائی ایئر ویز انٹرنیشنل کے کنٹری مینی...,Business,کراچی تھائی ایئر ویز انٹرنیشنل کے کنٹری مینیج...
3,اسلام آباد: وفاقی حکومت کا قرضہ صرف 8ماہ میں...,Business,اسلام آباد وفاقی حکومت کا قرضہ صرف ماہ میں ...
4,اسلام آباد: وفاقی حکومت کی جانب سے اعلان کرد...,Business,اسلام آباد وفاقی حکومت کی جانب سے اعلان کردہ...

## Preprocessing of Data
Data was cleaned that saved into column "Clean_Data"  We further remove some unnecessary words.
Stopwords are common words that are often filtered out during text processing in natural language processing (NLP) tasks. These words are considered to have little or no value in conveying the actual meaning of the text. We take list of 401 stopwords for topic modelling.

In [ ]:
df['Clean_Data'] = df['Clean_Data'].str.replace('شیئرٹویٹشیئرای میلتبصرے مزید شیئر', '')

In [ ]:
df['Clean_Data'] = df['Clean_Data'].str.replace('کیلیے', '')

In [ ]:
def remove_nonbreaking_space(text):
    return re.sub(r'\xa0', ' ', text)

df['Clean_Data'] = df['Clean_Data'].apply(remove_nonbreaking_space)

In [ ]:
documents = df['Clean_Data'].values.tolist()
print((documents[1]))
doc1=documents[1]

 پی ایس او کے مختلف اداروں پر واجبات  ارب سے تجاوز پی ایس او کے مختلف اداروں پر واجبات  ارب سے تجاوزشیئرٹویٹ علیم ملک  پير  اپريل    ارب  کروڑ کے ساتھ پاورسیکٹرسب سے بڑا نادہندہپی آئی اے کے ذمے  ارب۔ فوٹو فائل   ارب  کروڑ کے ساتھ پاورسیکٹرسب سے بڑا نادہندہپی آئی اے کے ذمے  ارب۔ فوٹو فائل   اسلام آباد پاکستان اسٹیٹ آئل  کا مالی بحران سنگین ہوگیا ہے اورپی ایس او کے مختلف اداروں کے ذمے واجبات  ارب کروڑ روپے کی ریکارڈ سطح پر پہنچ گئے ہیں۔  مختلف اداروں کی جانب سے پی ایس او کو باقاعدگی سے ادائیگی نہ کرنے کی وجہ سے پی ایس او مالیاتی بحران کا شکار ہوگیاہے اور عدم ادائیگیوں کی جانب سے پی ایس او مشکلات کا شکار ہوگیا ہے۔ دستاویز کے مطابق مختلف اداروں کی جانب سے پاکستان اسٹیٹ آئل کو  ارب سے زائد کی رقم واجب الادا ہے۔  پاور سیکٹر پی ایس او کا سب سے بڑا نا دہندہ ہے اور پاور سیکٹر نے پی ایس او کو  ارب  کرروڑ روپے کی ادائیگیاں کرنی ہیں۔ سرکاری دستاویز کے مطابق بجلی کی پیداواری کمپنیوں  نے پی ایس او کو ایک سو ترپن ارب روپے حبکو نے تراسی ارب چالیس کروڑ روپے اور کو ٹ ادو پاور کمپنی کیپکو نے پی ایس او کو تینتالیس ارب ستر کروڑ روپے ادا کرنے ہیں۔  دستاویزکے مطابق پی آئی اے نے پی ایس او کو  ارب  کروڑ روپے اور حکومت نے قیمتوں میں فرق کے کلیمز سے متعلق نو ارب ساٹھ کروڑ روپے ادا کرنے ہیں جبکہ سوئی نادرن گیس کمپنی لمٹیڈ نے ایل این جی کے واجبات کی مد میں پی ایس او کو پچیس ارب روپے کی ادائیگی کرنی ہے۔ مالی بحران کا شکار پی ایس او نے مختلف ملکی و غیر ملکی ریفائنریوں کو پندرہ ارب دس کروڑ روپے ادا کرنے ہیں۔  پی ایس او نے پارکو کو سات ارب بیس کروڑ روپے پاکستان ریفائنری لمٹیڈ کو دو ارب چالیس کروڑ روپے بائیکو دو ارب بیس کروڑ روپے اور اٹک آئل ریفائنری کو ایک ارب اسی کروڑ روپے ادا کرنے ہیں۔ دستاویز کے مطابق پی ایس او نے اینار کو اسی کروڑ روپے اور نیشنل ریفائنری لمٹیڈ کو ستر کر وڑ روپے ادا کرنے ہیں۔  دستاویز میں مزید بتایاگیاہے کہ پی ایس او نے ایل سی ایل این جی اور دیگر ادائیگیوں کی مد میں مجموعی طور پر پینسٹھ ارب ساٹھ کروڑ روپے فوری ادا کرنے ہیں۔ پی ایس او ذرائع نے بتایاکہ حکومت کی جانب سے پی ایس او کو باقاعدگی سے ادائیگیوں کی یقین دہانی کرائی گئی تھی تاہم اس پر ابھی تک کوئی عمل درآمد نہیں کیاگیا جس کی وجہ سے پی ایس او گزشتہ کئی سال سے مالی مشکلات کا شکار رہا ہے۔  ذرائع کا مزید کہناہے کہ اگر پی ایس او کو بروقت ادائیگیاں نہ کی گئیں تو سپلائی چین متاثر ہوسکتی ہے جس کے نتیجے میں ملک میں لوڈشیڈنگ کا دورانیہ مزید بڑھ سکتا ہے۔ اس سلسلے میں جب پاور ڈویژن کے ترجمان سے رابطہ کرنے کی کوشش کی گئی تو ان کا نمبر مسلسل بند جارہاتھا۔

In [ ]:
import nltk
stopwords=pd.read_csv('/content/drive/MyDrive/stopwords.txt',names=['List'])
# stopwords['List']

stopwords_ur=[]
for li in stopwords['List']:
  stopwords_ur.append(li)
print(len(stopwords_ur))
print(stopwords_ur)

401
['کی', 'ہیں', 'ہے', 'رہا', 'رہی', 'رہے', 'تھا', 'تھے', 'تھی', 'تھى', 'میں', 'کہ', 'کے', 'ہوتے', 'کہہ', 'بنانا', 'پھر', 'لکین', 'ہوتی', 'لیتی', 'ایسی', 'ائے', 'ہوئے', 'ہوۓ ', 'مگر', 'چاہے', 'کیے', 'تاکہ', 'تم', 'آکر', 'لگا', 'ہوگیئں', 'ليے', 'رہتی', 'ہوگئی', 'انھوں', 'چاہتے', 'پاگیئں', 'آنا', 'کروا', 'رکھ', 'آتی', 'یہاں', 'جیسا', 'چکے', 'کرئے', 'دیے', 'چکا', 'ملتا', 'کبھی', 'ایسا', 'کرسکیں', 'ہوسکے', 'سکیں', 'لہذا', 'چاہئے', 'وہیں', 'اٹھایا', 'جہنوں', 'ہمارے', 'لیے', 'آرہے', 'کرگیئں', 'بنانے', 'سکتا', 'وغیرہ', 'دے', 'ہوۓ', 'رہنے', 'ہوۓ', 'کئے', 'لگے', 'لگایا', 'لائے', 'کہے', 'کرے', 'رہئں', 'آگئے', 'کئی', 'کم', 'ملی', 'جنہیں', 'ہوئیں', 'تھیں', 'ابھی', 'پاگئیں', 'آئے', 'کرا', 'دیا', 'جہاں', 'آگئیں', 'کرتی', 'رہیں', 'کرتیں', 'دیتی', 'ہوگئے', 'ديتے', 'انہں', 'ایسے', 'رکھتے', 'رہتے', 'رکھی', 'کیں', 'كیا', 'وه', 'جنہيں', 'کروائی', 'دینا', 'جسے', 'جاتی', 'اسکی', 'ملے', 'کرگئى', 'جن', 'آپکو', 'جنہوں', 'دیئے', 'والی', 'جبکہ', 'دیگر', 'آپکا', 'رکھنے', 'انہىں', 'کيے', 'یعنی', 'كيے', 'بننے', 'جاملے', 'ليكن', 'كرنے', 'كر', 'آيا', 'كرگئى', 'پھر', 'کچھ', 'آتے', 'دینے', 'اپ', 'ہونا', 'انہیں', 'لگی', 'آنے', 'کرلی', 'ہوگئى', 'پایا', 'آپکے', 'بنائی', 'کرديا', 'لا', 'رکهنے', 'كہ', 'بنا', 'كرديا', 'ركھى', 'ميں', 'ركھتے', 'كروائى', 'حتی', 'لایا', 'لیتے', 'ہمیں', 'گئى', 'بنائے', 'تاہم', 'پھر بھی', 'بنايا', 'دىے', 'ايم اے او', 'كئى', 'پڑا', 'رکھے', 'انہی', 'دیں', 'ليکر', 'البتہ', 'ہى', 'کرکے', 'پائی', 'لینا', 'دہی', 'دئیے', 'گوکہ', 'دئيے', 'كيں', 'جایا', 'کروایا', 'كیے', 'ہاں', 'کہنا', 'کیلئے', 'ہوگا', 'دیکھتے', 'آرہے', 'آگیا', 'اپنے آپ', 'طرف سے', 'ملا', 'آپكى', 'پھر بھی', 'كرگئے', 'آپکی', 'ليا', 'ديے', 'كے', 'رکھى', 'رکھتا', 'کرايا', 'چلے', 'آتا', 'لاکر', 'جیسے', 'کرليا', 'کیا ہے', 'وہاں', 'لینے', 'پاگئے', 'ہر', 'رکھنا', 'كيا', 'آیا', 'هے', 'كى', 'کرایا', 'حاصل', 'آگئى', 'دى', 'کبهی', 'جاسكتا', 'اسى', 'كی', 'كہا', 'كرو', 'اور', 'سے', 'کا', 'کى', 'سب', 'کو', 'كو', 'نے', 'اس', 'ہيں', 'پر', 'کر', 'ايک', 'كا', 'ہو', 'بهی', 'ایک', 'یہ', 'نہيں', 'ان', 'کيا', 'تو', 'وہ', 'لئے', 'کرنے', 'آپ', 'کہا', 'گيا', 'جو', 'گا', 'ہی', 'جائے', 'نہ', 'جب', 'اپنے', 'جس', 'دیا', 'ہوئے', 'تک', 'بعد', 'انہوں', 'رہے', 'ليکن', 'گی', 'کریں', 'گے', 'کرتے', 'ہونے', 'گئے', 'اپنی', 'والے', 'بہت', 'کسی', 'جا', 'تهی', 'یا', 'گئی', 'ہم', 'ہوں', 'کيلئے', 'زیادہ', 'رہا', 'طرح', 'اگر', 'اب', 'ہوا', 'دی', 'ہوتا', 'کام', 'جب', 'جو', 'گا', 'لیکن ', 'کرتى ', 'کرگئی ', 'گیا ', 'اسی', 'کیا', 'ہوئی', 'انہيں', 'جانا', 'جانے ', 'ہوئی ', 'کرگئے ', 'دیا', 'کو ', 'میں', 'ہوئے', 'ایک', 'تھے ', 'آپ ', 'نہیں', 'لیکن', 'تھی', 'جو', 'اور', 'کرتى', 'کرتا', 'کرگئی', 'کر', 'جاتے', 'لئے', 'گیا', 'کہا ', 'جاتا', 'اس ', 'جاتى', 'کرنا', 'کسی', 'بھی', 'طرف', 'ہوتا', 'لیکن', 'یہ', 'ہی', 'یا', 'اگرچہ', 'کہ', 'نے', 'رکھو', 'کرو', 'جانے', 'انہيں ', 'ديا', 'سے', 'کرگئے', 'پر', 'ہوئى', 'ان', 'اپنى', 'اپنا', 'ذریعے', 'رکھا', 'ہونے', 'اپنے', 'بعد', 'پاگئى', 'دیتے', 'كرتے', 'ہوتى', 'کہتے', 'دی', 'کرگئیں', 'اسے', 'اسی', 'لیا', 'لے', 'لی', 'کس', 'کسی', 'لیے', 'آئی', 'بنے', 'کچھ ', 'ہی', 'کرتی', 'کرتا', 'لئے', 'طور', 'نہیں', 'بلکہ', 'کیونکہ', 'کیوں', 'جس ', 'گئی', 'ہونے', 'وجہ', 'ہوگیا', 'لينے']

# BERTopic Training

In [ ]:
#create custom embedding
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('sentence-transformers/distiluse-base-multilingual-cased-v2')
embeddings = model.encode(documents, show_progress_bar=True)
print(embeddings)

modules.json:   0%|          | 0.00/341 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/2.69k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/610 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/539M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/531 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/996k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.96M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

2_Dense/config.json:   0%|          | 0.00/114 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.58M [00:00<?, ?B/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

[[ 0.00916042  0.06687659  0.00793992 ...  0.03491772 -0.02360609
   0.01003345]
 [ 0.04833498  0.00919292  0.00568508 ...  0.02414999 -0.02264939
  -0.00885205]
 [ 0.01044563  0.04916572 -0.02431903 ...  0.02065906 -0.02522849
   0.03500259]
 ...
 [ 0.0157033   0.07207946 -0.05418859 ...  0.00750634 -0.02253509
  -0.01156019]
 [ 0.00571777  0.00127601  0.03927448 ... -0.04930213  0.01686148
  -0.00087841]
 [-0.00262932  0.04106253  0.0123721  ...  0.02529592  0.01291248
   0.02558282]]

In [ ]:
#pass vectorizer_model to bertopic for stopwords removal
from sklearn.feature_extraction.text import CountVectorizer

vectorizer_model = CountVectorizer(stop_words= stopwords_ur)

In [ ]:
#ClassTfidf for top words
from bertopic.vectorizers import ClassTfidfTransformer

ctfidf_model = ClassTfidfTransformer(bm25_weighting=True, reduce_frequent_words=True)

In [ ]:
#UMAP for dimention reduction
from umap import UMAP
dim_model = UMAP(n_neighbors=10, n_components=5, random_state=42)

In [ ]:
# # #KMeans used for clustering
from sklearn.cluster import KMeans

cluster_model = KMeans(n_clusters=5, random_state=42)

In [ ]:
np.random.seed(42)

In [ ]:
topic_model = BERTopic(language="urdu", low_memory=True ,calculate_probabilities=True, vectorizer_model=vectorizer_model, top_n_words=10, umap_model=dim_model,ctfidf_model=ctfidf_model, hdbscan_model=cluster_model)

In [ ]:
#Fit documents in bertopic
topics, probs = topic_model.fit_transform(documents,embeddings)

In [ ]:
print(probs)

None

In [ ]:
#topics that assign to each document
print(topics)

[2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 4, 0, 2, 4, 2, 2, 2, 2, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 3, 3, 3, 3, 3, 0, 0, 3, 0, 3, 3, 0, 3, 0, 3, 3, 3, 3, 3, 1, 4, 4, 4, 1, 4, 3, 4, 4, 0, 4, 4, 4, 0, 4, 4, 4, 4, 4, 4, 0, 3, 0, 0, 3, 3, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0]

In [ ]:
topic_model.get_topic_freq()

   Topic  Count
1      0     28
3      1     20
0      2     18
4      3     18
2      4     17

In [ ]:
document_topics = topic_model.get_topics()

In [ ]:
#topics with score
print(document_topics)

{0: [('استعمال', 0.3062610610546161), ('رنز', 0.2979714722489764), ('گھر', 0.2971189246116796), ('دور', 0.2965064757699254), ('دنیا', 0.28433004325102396), ('قدیم', 0.28191209596494216), ('قبل', 0.27461843013320864), ('پہلے', 0.2724209446433291), ('دریافت', 0.26450022940360346), ('نسو', 0.26294640892763005)], 1: [('فلم', 0.5126266432704637), ('بالی', 0.49380481602308285), ('ووڈ', 0.4780604250806612), ('اداکارہ', 0.450719691188612), ('خان', 0.44361403866713917), ('میڈل', 0.4393999617717059), ('ساتھ', 0.4368771041452682), ('صفہ', 0.3908982155994856), ('ماہرہ', 0.3814331344882132), ('میٹرز', 0.3814331344882132)], 2: [('ارب', 0.5862166159439897), ('ٹیکس', 0.5561308496210363), ('بینک', 0.5258126937644019), ('روپے', 0.5208649385657871), ('لاکھ', 0.5116976890154278), ('کروڑ', 0.500101867664878), ('مالی', 0.49376204584816), ('او', 0.48940136384641403), ('پی', 0.4628873613765677), ('ایس', 0.4509818699341509)], 3: [('کینسر', 0.47368497386964964), ('منہ', 0.45296663480411903), ('ڈاکٹر', 0.39062460322928927), ('خون', 0.3871239196698648), ('پاکستان', 0.38421029579544025), ('مریضوں', 0.383576068109427), ('فالج', 0.36893267176035943), ('ماہرین', 0.359177265359626), ('چھالیہ', 0.3535910024786791), ('میڈلز', 0.3408326382865303)], 4: [('گیمز', 0.41580526288920727), ('سندھ', 0.41508501338248766), ('محمد', 0.39812635459918005), ('پاکستان', 0.3979004244805038), ('برانز', 0.39624240692154766), ('جی', 0.3855032541824153), ('سلور', 0.38407042291804167), ('گولڈ', 0.3817008966801263), ('ٹیم', 0.37629857718773185), ('ایف', 0.374466354522002)]}

In [ ]:
#shows which documents assign to specific topic
topic_model.get_representative_docs(topic=None)

{0: ['  انہیں کھانے سے ذائقے کے ساتھ ساتھ خوشگواریت کا بھی احساس ہوتا ہے۔ کھانوں میں ان مسالوں کی موجودگی کا خیال رکھنا بہت ضروری ہے کیوں کہ یہ مسالے خوش ذائقہ ہونے کے ساتھ ساتھ مفید بھی ہیں۔ انہیں اچھی طرح صاف کرکے ڈبوں میں محفوظ کر لیا جائے تاکہ بہ وقت ضرورت کام آسکیں۔  یہاں ہم چیدہ چیدہ مسالوں کے فوائد اور ان کے مفید استعمال کا ذکر کرتے ہیں تاکہ آپ ان مسالوں کی اہمیت سے آگاہ ہوسکیں اور اپنے کھانوں کو مزے دار بنانے میں ان کی مدد لے سکیں۔ کلونجی کلونجی کے چند دانے کھانے میں ضرور استعمال کرنے چاہییں کلونجی میں بہت سی بیماریوں کا علاج موجود ہے۔ معدے اور پیٹ کے امراض کے علاوہ آنتوں کے درد دماغی کم زوری اور فالج سے بچاؤ کا حل بھی کلونجی میں موجود ہے۔ اچار میں اس کا استعمال کیا جاتا ہے بلکہ اچار اس کے بغیر مکمل نہیں ہوتا۔ اس میں کاربوہائیڈریٹ فاسفورس اور فولاد کے مرکبات پائے جاتے ہیں۔  ایک تجزیاتی رپورٹ کے مطابق کلونجی میں ایک پیلے رنگ کا مادہ کیروٹینبھی پایا جاتا ہے جو جگر میں پہنچ کر وٹامن اے میں تبدیل ہوجاتا ہے۔ کلونجی جسم کی قوت مدافعت کو بڑھاتی ہے۔ ایک کپ گرم پانی میں نصف چائے کا چمچہ کلونجی کا تیل ملا کر نہار منہ استعمال کرنے سے دمہ کھانسی اور الرجی سے نجات مل سکتی ہے۔  دار چینی دارچینی کھانے کے ذائقے کو مزید بہتر بناتی ہے۔ یہ بلڈ پریشر اور کولیسٹرول کے مریضوں کے لیے بے حد مفید ہے۔ ایک چھوٹا چائے کا چمچہ دار چینی پاؤڈر کو ایک چمچہ شہد میں ملاکر ایک کپ پانی میں ڈال کر پی لیں اس سے کولیسٹرول کا لیول کم رہے گا۔ علاوہ ازیں دار چینی کا استعمال ہڈیوں کے درد میں بھی کمی کرتا ہے جب کہ ہی نزلہ و کھانسی میں بے حد مفید ہے۔  کالی مرچ کالی مرچ مسالوں میں بنیادی اہمیت کی حامل ہے۔ یہ آنتوں کے کینسر کو جسم میں پھیلنے سے روکنے میں مدد گار ثابت ہوتی ہے۔ یہ نزلہ زکام میں کمی پیدا کرتی ہے۔ فرائی انڈے پر پسی ہوئی کالی مرچ ڈال کر استعمال کرنے سے اس کا ذائقہ دوبالا ہوجاتا ہے۔ یہ قوت قلب کو بڑھاتی ہے اور معدے میں گیس بننے کا عمل کم کرتی ہے۔ رائتے اور پلاؤ میں ثابت کالی مرچ کا استعمال کیا جاتا ہے جس کا ایک الگ ہی مزہ ہوتا ہے۔ کالی مرچ میں رسولی کے کینسر کے خلاف مزاحمت پائی جاتی ہے۔ کالی مرچ کھانے کی رغبت اور اشتہا کو بھی بڑھاتی ہے۔  چھوٹی الائچی چھوٹی الائچی ایک خوش بودار اور لطیف ذائقہ رکھتی ہے اسی وجہ سے اسے میٹھے کھانوں کی تیاری میں استعمال کیا جاتا ہے۔ یہ منہ کی بدبو کھانسی اور ہچکی سے نجات دلاتی ہے۔ یہ پتھری ختم کرنے کی بھی صلاحیت رکھتی ہے۔ وزن کم کرنے لیے چھوٹی الائچی کا استعمال بہت ضروری ہے۔  چھوٹی الائچی دو عدد ادرک ایک چھوٹا ٹکڑا دار چینی ایک ٹکڑا لونگ ایک عدد پودینے کی پتیاں چند لے کر ڈیڑھ کپ پانی میں اتنا پکائیں کہ ایک کپ رہ جائے پھر اس میں لیموں کا رس اور حسب ذائقہ شہد ملا کر صبح شام پی لیں اس سے وزن میں خاطر خواہ کمی واقع ہوگی۔ اس کے علاوہ چھوٹی الائچی منہ کے چھالوں کا بھی بہترین علاج ہے اسے چبانے سے کھانا آسانی سے ہضم ہوجاتا ہے اس لیے اکثر کھانے کے بعد الائچی بڑے شوق سے کھائی جاتی ہے۔  زیرہ زیرہ چاہے سفید ہو یا کالا اس کا استعمال مفید ہے یہ معدے آنتوں اور پھیپھڑوں کو طاقت فراہم کرتا ہے۔ زیرہ ایک ماشہ باریک پیس کر کھانے میں ملانے سے جگر کو تقویت ملتی ہے۔ یہ پلاؤ اور کڑی کی تیاری میں عام طور سے استعمال ہو تا ہے۔ زیرہ بلغم کو دور کرتا ہے۔ شوگر کے مرض میں بھی یہ ایک بہترین دوا کا کام دیتا ہے۔ اس میں وٹامن ای موجود ہوتا ہے جو بڑھتی عمر کے اثرات کو روکتا ہے۔ جلد کی خارش کو ختم کرنے میں بھی بڑی اہمیت کا حامل ہے۔ ابلتے ہوئے پانی میں تھوڑا سا زیرہ شامل کر کے نہانے سے آپ خود کو تازہ دم محسوس کریں گے۔  سونف سونف کھانوں کو خوش بودار بناتی ہے۔ یہ خون کو صاف کرنے میں مدد دیتی ہے۔ اس کے استعمال سے ہچکی ختم ہوجاتی ہے۔ یہ معدے کی جلن کو بھی کم کرتی ہے۔ آدھا چمچہ سونف کا پاؤڈر گرم دودھ میں ملا کر پینے سے نزلہ زکام سے چھٹکارا حاصل ہوجاتا ہے۔  لونگ لونگ کے استعمال سے دانت اور پیٹ کے درد میں کافی فائدہ ہوتا ہے۔ لونگ کے تیل کو گرم کرکے اس کی بھاپ لینے سے سانس کی تکلیف میں کمی آتی ہے۔ لونگ سے چہرے کے مہاسے ختم کرنے میں مدد ملتی ہے۔ لونگ پیس کر اس میں شہد اور لیموں کا رس ملا کر پندرہ منٹ کے لیے چہرے پر لگا رہنے دیں۔ اس سے آپ کی جلد صاف ہوجائے گی اور کھردرا پن بھی ختم ہو جائے گا۔ لونگ جراثیم کش بھی ہے اس کا تیل کیڑوں کو بھگاتا ہے۔  میتھی دانہ میتھی دانہ مختلف کھانوں کو خوش بو دار بنانے کے لیے استعمال کیا جاتا ہے۔ اچار کے مسالے میں میتھی دانہ ضرور شامل کیا جاتا ہے۔ اسے کھانے میں شامل کرنے سے اعصابی تھکاوٹ دور ہوتی ہے۔ یہ کمر اور جگر کے درد کو کم کرنے میں معاون ثابت ہوتا ہے۔ میتھی دانے کا جوشاندہ بناکر پینے سے گلے کا درد اور سوجن ٹھیک ہوجاتی ہے۔ میتھی موسم سرما کے امراض تلی کے ورم اور گنٹھیا وغیرہ کے لیے بھی مفید ہے۔  سبز دھنیا خشک سبز دھنیا پیس کر کھانوں میں عام استعمال کیا جاتا ہے۔ یہ جلد کی سوزش منہ کے السر کے خاتمے کے لیے اہم ہے۔ علاوہ ازیں خون کی کمی کو بھی پورا کرتا ہے۔ یہ بھوک میں اضافہ کرتا ہے اور پٹھوں کے درد کے علاج کے لیے اہمیت رکھتا ہے۔  ان تمام فوائد کے باوجود کھانے میں ان سب مسالوں کی زیادتی نقصان دہ ثابت ہوسکتی ہے اس لیے کھانوں میں ان کی مقدار مناسب رکھنی چاہیے تاکہ آپ ان مسالوں سے بھرپور انداز سے مستفید ہوسکیں۔ موسم کے شدت اختیار کرنے سے قبل اگر خواتین باقاعدگی سے چند اشیا کا استعمال گھر کے ہر فرد کو شروع کروادیں تو نہ صرف سردی کھانسی اور ملیریا سے بچا جاسکتا ہے بلکہ نزلہ زکام  سینے کی جکڑن  بلغم اور بچوں کی پسلیاں چلنے جیسے مسائل سے بھی محفوظ رہ سکتے ہیں۔',
  '  بازار میں ایک تو ویسے ہی بے تحاشا رش تھا۔ دوسرے دکانوں کے آگے قائم ناجائز تجاوزات گدھا گاڑیوں اور رکشوں نے نقل و حرکت جام کرکے رکھ دی تھی۔یہاں تک کہ پیدل چلنے والوں کا بھی گزرنا محال ہورہا تھا۔ اوپر سے لوگوں اور ٹریفک کا شور غرض ایک افراتفری کا عالم تھا۔ ایسے میں اچانک ایک بچے کے زور زور سے رونے کی آواز سب شوروغل پر غالب آگئی۔  جب پیچھے مڑ کر دیکھا تو ایک عجیب منظر دکھائی دیا۔ ایک موٹر سائیکل پر میاں بیوی اور آگے ایک بچہ سوار تھے۔ بچے کے ہاتھ میں کافی سارے کھلونوں کے شاپر تھے جبکہ ماں کے ہاتھ اور موٹر سائیکل کے ہینڈل پر بھی سودا سلف کے شاپر لٹک رہے تھے۔ بچہ زور و شور سے روئے چلا جارہا تھا اور ماں باپ کے سمجھانے اور پیار کرنے کے باوجود چپ ہونے میں نہیں آ رہا تھا۔ پتا یہ چلا کہ وہ اپنی پسند کا ایک اور کھلونا لینے پر بضد تھا اور ماں باپ اس ضد سے باز رکھنے کے لیے اسے منانے کی کوشش کررہے تھے۔ اب معلوم نہیں کہ ان کے پاس وہ مہنگا کھلونا خریدنے کے لیے پیسے نہیں تھے یا کوئی اور بات تھی لیکن بچہ اپنی ضد چھوڑنے کو بالکل تیار نہیں تھا اور مسلسل روئے چلا جارہا تھا۔ بہت سے لوگ رک کر دلچسپی سے یہ سارا منظر دیکھ رہے تھے۔ آخر کار بچے کے باپ نے تنگ آکر موٹر سائیکل چلانا چاہی۔ اب صورتحال یہ تھی کہ بچے کا رونا دھونا اور شدت اختیار کرگیا ساتھ ساتھ وہ موٹر سائیکل پر بیٹھے بیٹھے ہاتھ پاؤں بھی مارنے لگا تھا۔ صاف نظر آرہا تھا کہ اسے سمجھانا عبث ہے۔ بچے کے باپ کے لیے اتنے رش میں موٹر سائیکل پر لدے سامان اور اس پر سوار بیوی بچے کے ساتھ موٹر سائیکل چلانا اور اسے سنبھالنا ایک مشکل کام ثابت ہورہا تھا۔ اوپر سے سب لوگ یہ معاملہ دیکھ دیکھ کر محظوظ ہورہے تھے۔ خجالت اور پریشانی نے بچے کے باپ کی حالت غیر کردی اور اس نے بچے کو دو تین تھپڑ رسید کیے مگر اس کا ردعمل بچے کے مزید رونے کی صورت میں نکلا۔ جیسے تیسے اس شخص نے موٹر سائیکل سنبھالی اور وہاں سے روانہ ہوگیا۔  ایسے اور دیگر کئی واقعات ہم اپنی روزمرہ زندگی میں مشاہدہ کرتے ہیں۔ کہیں بچے گھر میں اپنی ضد منوانے کے لیے رونے کو ایک حربے کے طور پر استعمال کرتے ہیں تو کہیں سکولوں میں اساتذہ کی مار سے بچنے کے لیے پہلے ہی رونا شروع کردیتے ہیں۔ کہیں مذاق ہی مذاق میں کسی کو اگر اچانک ڈرا دیا جائے تو لوگ  روپڑتی ہیں۔ اسی طرح مختلف جذبات مثلاً غم و یاس یا کسی تکلیف میں مبتلا ہوکر لوگوں کی آنکھیں چھلک پڑتی ہیں۔ اور تو اور اکثر لوگوں کے خوشی کے مواقع پر یا بہت زیادہ ہنسنے کے باعث بھی آنکھوں سے آنسو رواں ہوجاتے ہیں۔ آخر ایسا کیوں ہوتا ہے انسان غمی خوشی یا دیگر مواقع پر اپنے جذبات کا اظہار کرتے وقت رو کیوں پڑتا ہے یہ سوال بہت اہم ہے۔  انسان جب پیدا ہوتا ہے تو روتا ہوا اس دنیا میں آتا ہے۔ سائنس دان کہتے ہیں کہ اس موقع پر رو کر بچہ اپنے جسمانی اعضاء مثلاً پھیپھڑے وغیرہ اور سانس لینے کے عمل کو متحرک کرتا ہے۔ بعد میں وہ جب تک بولنے کے قابل نہیں ہوجاتا تو اپنی ضروریات جیسے بھوک کے وقت خوراک وغذا کے حصول وغیرہ کے لیے رو کر اپنی طرف توجہ مبذول کرواتا ہے یا پھر اپنی کسی تکلیف کا اظہار بھی رو کر ہی کرتا ہے۔ جب انسان دنیا سے جاتا ہے تو اس کے پیارے اور چاہنے والے اس کے بچھڑنے کا غم رو کر مناتے ہیں۔ غرض رونا مختلف جذباتی کیفیات کے اظہار کا ایک ذریعہ ہے اور یہ ایک فطری رویئے کا نام ہے۔  سائنس دان اس ضمن میں زیادہ پر یقین نہیں ہیں کہ انسان کیوں روتا ہے۔ چارلس ڈارون نے ایک بار کہا تھا کہ جذبات میں بہہ نکلنے والے آنسوؤں کا کوئی مقصد نہیں ہوتا۔ آج ایک سو پچاس سال گزرنے کے باوجود جذبات کی رو میں بہہ کر رونا انسانی جسم کے حیران کن اسراروں میں سے ایک ہے۔ گو کچھ دیگر انواع بھی درد تکلیف یا پریشانی کی صورت میں آنسو بہاتی ہیں لیکن یہ صرف انسان ہی ہیں کہ جن کی آنکھیں کسی بھی احساس تلے چھلک پڑتی ہیں۔ آخر ایسا کیوں ہوتا ہے  اس موضوع پر تحقیق کرنے والے عام طور پر اپنی توجہ حیاتیاتی عمل کے بجائے جذباتی محسوسات پر زیادہ مرکوز رکھتے ہیں۔ ہالینڈ کی ٹلبرگ یونیورسٹی کے پروفیسر ایڈونگر ہوئٹس لکھتے ہیں کہ اگر کسی انسان کے معدے میں تتلی پائی جائے تو یہ بات شائد سائنس دانوں کے لیے حیرت انگیز یا دلچسپی کا باعث نہیں ہو گی بلکہ ان کے لیے محبت جیسے احساسات پر تحقیق کرنا زیادہ دلچسپی کا باعث ہوتا ہے۔ یاد رہے کہ پروفیسر ایڈونگر ہوئٹس کی وجہ شہرت ان کی شہرۂ آفاق کتاب صرف انسان ہی کیوں روتے ہیں بھی ہے۔ رونا صرف اداسی کی علامت ہی نہیں ہے جیسا کہ پروفیسر ایڈونگر ہوئٹس اور دوسرے ماہرین ظاہر کرتے ہیں بلکہ یہ جذبات و احساسات کے مختلف سلسلوں سے جڑا ایک عمل ہے۔  جن میں ہمدردی سے لے کر حیرت اور غصے سے لے کر غم سمیت بہت سے محسوسات شامل ہیں۔ جب ہم کسی کی محبت میں گرفتار ہوتے ہیں تو ہمارے اندر کا موسم بہت حسین ہوجاتا ہے جس کا پتا صرف ہمیں ہی ہوتا ہے مگر آنسو ایسی چیز ہیں جو دوسروں کو بھی نظر آتے ہیں۔ یہ وہ نئی آگاہی ہے جو رونے کی وجوہات ڈھونڈنے والے محققین کے علم میں اب آئی ہے۔  صدیوں تک لوگوں کا خیال تھا کہ آنسو دل میں پیدا ہوتے ہیں۔ اس بارے میں ء میں یہ ایک مقبول نظریہ تھا کہ جذبات خاص طور پر محبت کے جذبات دل کو حرارت پہنچاتے ہیں۔ اس حرارت کو معتدل کرنے کے لیے دل آبی بخارات پیدا کرتا ہے اور دل سے یہ بخارات اوپر سر کی جانب اٹھتے ہیں اور آنکھوں کے پاس پہنچ کر کثیف ہوکر آنسوؤں کی صورت بہہ نکلتے ہیں۔ بالآخر ء میں ڈنمارک کے ایک سائنس دان نیلسن سٹینسن نے دریافت کیا کہ آنسوؤں کا منبع دراصل لیکریمل نامی گلینڈ ہے۔ اس دریافت کے بعد ہی سائنس دانوں نے سوچنا شروع کیا کہ آنکھوں سے پھوٹنے والے اس مائع کا ارتقائی فائدہ کیا ہے۔ سٹینسن کا نظریہ یہ تھا کہ آنسو صرف آنکھوں کو نم رکھنے کا ایک طریقہ ہیں۔  اپنی کتاب میں پروفیسر ونگر ہوئٹس نے آٹھ تقابلی نظر یات کا تذکرہ کیا ہے۔ ان میں سے کچھ تو بالکل مضحکہ خیز ہیں۔ جیسے ء کا یہ نظریہ کر انسان آبی گوریلوں کی ارتقائی شکل ہے اور آنسو انہیں نمکین پانی میں رہنے میں مدد دیتے تھے۔ باقی نظریات بھی بغیر کسی ثبوت کے اس بات پر دلالت کرتے تھے کہ رونا جسم میں موجود فاسد مادے خارج کرنے کا ایک ذریعہ ہے جو جذباتی یا ذہنی دباؤ کے نتیجے میں پیدا ہوجاتے ہیں۔ یہ نظریہ ء میں ایک حیاتیاتی کیمیا دان ولیم فرے نے پیش کیا تھا۔ شواہد مگر کچھ مزید نئے نظریات کی حمایت کرتے نظر آتے ہیں جو قرین قیاس ہیں۔  ان میں سے ایک نظریہ یہ بھی ہے کہ آنسوؤں کا محرک سماجی تعلقات اور انسانی روابط ہیں۔ انسان اپنی ابتدائی عمر سے ہی رونا شروع کردیتا ہے تاکہ اپنے نزدیک موجود دوسرے انسانوں کے ساتھ رابطہ قائم کرسکے۔ جب ہم اس دنیا میں آتے ہیں تو جسمانی طور پر خود کچھ بھی کرنے سے قاصر و معذور اور اپنی ضروریات جیسے خوراک وغیرہ کے حصول کے حوالے سے لاچار ہوتے ہیں۔ اگرچہ وقت گزرنے کے ساتھ ساتھ ہم اپنی ضروریات پورا کرنے کے قابل ہوتے چلے جاتے ہیں مگر پھر بھی بڑے ہوجانے کے باوجود وقت کے دھارے میں بہتے ہوئے دفتاً فوقتاً ہمیں سہاروں کی ضرورت پڑتی رہتی ہے۔ خاص طور پر ان جذباتی لمحات میں کہ جب ہم اپنے آپ کو تنہا اور بے یارو مددگار پاتے ہیں تو ہم ان سہاروں کی ضرورت کو نظر انداز نہیں کرسکتے۔  جوناتھن روٹنبرگ جو یونیورسٹی آف ساؤتھ فلوریڈا میں نفسیات کے پروفیسر اور انسانی جذبات و محسوسات کے ایک محقق ہیں کا کہنا ہے کہ  رونے کا مطلب یہ ہوتا ہے کہ انسان دوسرے لوگوں کو یہ بتانا چاہ رہا ہوتا ہے کہ وہ کسی ایسی مشکل میں پھنس چکا ہے یا کسی ایسی اہم جذباتی کشمکش کا شکار ہے جس سے نکلنا یا جسے حل کرنا عارضی طور پر ہی سہی کم از کم اس کی بساط سے باہر ہے۔ اس موضوع پر نئی تحقیق یہ بھی بتاتی ہے کہ آنسو تکلیف میں مبتلا شخص کی طرف سے دوسرے لوگوں کی توجہ اپنی طرف مبذول کرنے کے لیے نکلتے ہیں جو محض باتوں کے ذریعے اپنی پریشانی دوسروں کو بتانے کی نسبت زیادہ اثر انگیز ثابت ہوتے ہیں۔  فروری ء میں شائع ہونے والی ایک رپورٹ کے مطابق تحقیق کاروں نے یہ نتیجہ اخذ کیا کہ آنسو لوگوں کے دلوں میں ہمدردی کے جذبات کو متحرک کردیتے ہیں۔ کچھ لوگوں کو تکلیف میں مبتلا ایک روتے ہوئے شخص کی تصویر دکھائی گئی تو انہوں نے اس کے لیے اپنے اندر ہمدردی کے جذبات زیادہ محسوس کیے اور جب انہیں اسی شخص کی بغیر آنسوؤں والی تصویر دکھائی گئی تو اس نے ان کے دلوں پر نسبتاً وہ اثر نہیں کیا جو پہلے ہوا تھا۔  سائنس دانوں کو یہ شواہد بھی ملے ہیں کہ جذبات میں نکلنے والے آنسو ان آنسوؤں سے مختلف ہوتے ہیں جو پیاز چھیلتے وقت آنکھوں سے نکلتے ہیں۔ اس کے علاوہ خامروں  تحمیات  میٹابولیٹیز  اور الیکڑو لائٹس یعنی برق پاش  کی وجہ سے جو آنسو بنتے ہیں ان کی نسبت جذبات کی رو میں بہہ نکلنے والے آنسوؤں میں پروٹین کی مقدار زیادہ ہوتی ہے۔  ایک مفروضہ یہ بھی ہے کہ یہ پروٹین سے بھر پور مواد جذبات کی وجہ سے نکلنے والے آنسوؤں کو زیادہ چیچپا اور لعاب دار بنا دیتا ہے جس کی وجہ سے یہ آنسو جلد پر چپک جانے سے چہرے پر بہت آہستگی کے ساتھ بہتے ہیں اور یوں دوسرے لوگوں کی زیادہ توجہ کھینچ لینے میں کامیاب ہوجاتے ہیں۔ یہ آنسو دوسروں کو یہ باور کرواتے ہیں کہ ہم کمزور اور غیر محفوظ ہیں۔ اور یہ بات مسلمہ ہے کہ عدم تحفظ کا احساس انسانی روابط میں ایک بہت حساس مسئلہ ہے۔ جب انسان کسی دوسرے انسان کو عدم تحفظ کا شکار دیکھتا ہے تو اس کے اندر کا عدم تحفظ بھی بیدار ہوجاتا ہے اور اس کے اندر اس دوسرے انسان کے لیے ہمدردی کے جذبات امڈ آتے ہیں۔ یونیورسٹی کالج لندن میں نیورلوجسٹ برائے انسانی روئیے مائیکل ٹرمبل کہتے ہیں کہ وقت کے کسی خاص لمحے میں ایک ایسا انقلابی دورانیہ بھی آتا ہے جب آنسو خود بخود دوسروں کے دلوں میں ہمدردی کے جذبات موجزن کر دیتے ہیں۔  اس بارے میں ایک اور نظریہ جو دلوں کو ذرا کم چھولینے والا ہے وہ یہ ہے کہ محققین کے نزدیک بڑے بھی بچوں ہی کی طرح آنسوؤں کو اپنی من پسند چیزوں کے حصول کے لیے بطور ایک ہتھیار استعمال کرتے ہیں۔ چاہے وہ ایسا جانتے بوجھتے کریں یا لاشعوری طور پر بے جانے بوجھے یہ حربہ آزمائیں۔ روٹنبرگ کہتے ہیں کہ ہم یہ بات بہت پہلے جان چکے ہیں کہ آنسو دوسروں کے غصے کو بجھانے کی طاقت رکھتے ہیں۔ ان کے مطابق آنسو پیار کرنے والوں کے جھگڑے کے بیچ ایک لازمی کردار کی حیثیت رکھتے ہیں۔ خاص طور پر جب ایک فریق غلطی پر ہو اور چاہتا ہو کہ دوسرے اسے اس غلطی پر معاف کردیں۔  ایک اور تحقیق جو سائنس نامی جریدے میں شائع ہوئی اور جس کا حوالہ وسیع پیمانے پر دیا جاتا رہا یہاں تک کہ میڈیا میں بھی اس کے بڑے چرچے ہوئے یہ بتاتی ہے کہ عورتوں کے آنسوؤں میں ایک ایسا مادہ پایا جاتا ہے جو مردوں کو صنفی کشش کے برعکس ان کے ہمدردی کے احساس کو زیادہ متاثرومتحرک کرتا ہے۔  لیکن توجہ طلب بات یہ ہے کہ ان سب باتوں اور نظریات کا مطلب کیا ہے یہ وہ سوال ہے کہ جس کی طرف اب سارے محققین کی توجہ مبذول ہورہی ہے۔ رونے کے موضوع پر تحقیق کرنے والے دنیا کے چند بڑے ماہرین میں سے ایک مائیکل ٹرمبل کہتے ہیں کہ ہم ان لوگوں کے بارے میں کچھ بھی نہیں جانتے جو بالکل نہیں روتے۔ اب یہاں یہ سوال پیدا ہوتا ہے کہ اگر آنسو انسانی تعلقات میں اتنی ہی اہمیت کے حامل ہیں تو پھر وہ لوگ جو کبھی نہیں روتے کیا وہ کم سماجی روابط رکھتے ہیں جی ہاں متعدد سرویز اور ریسرچز اس بنیادی بات کی تائید کرتی ہیں۔  جرمنی کی کاسل یونیورسٹی کے پروفیسر اور کلینیکل سائکولوجسٹ کورڈ بینیک کے بقول جب انہوں نے ایک سو بیس افراد کے بے تکلفانہ تھراپی سٹائل انٹرویوز کیے اور یہ جاننے کی کوشش کی کہ جو لوگ نہیں روتے کیا ان لوگوں سے مختلف ہوتے ہیں جو روتے ہیں تو ان کی تحقیق کے مطابق نہ رونے والے لوگوں کے اندر اپنے سماجی تعلقات کے کمزور روابط کے تجربات کو دوسرے لوگوں سے بٹانے اور بیان کرنے کا رجحان پایا جاتا ہے۔ آنسو نہ بہانے والے لوگوں میں منفی اور جارحانہ احساسات زیادہ موجود ہوتے ہیں جیسا کہ غصہ غیظ و غضب اور نفرت وغیرہ۔ اس حوالے سے ابھی مزید تحقیق کی ضرورت ہے کہ کیا نہ رونے والے لوگ واقعی دوسروں سے مختلف ہوتے ہیں۔  ابھی تک کی تحقیق سے یہ لگتا ہے کہ شاید رونا محض باہمی مفادات حاصل کرنے کا ایک ذریعہ ہے اور ضروری نہیں کہ نہ رونا کوئی غیر صحت بخش چیز ہو اور نہ ہی عملی طور پر ایسے کوئی شواہد ملے ہیں کہ جس سے یہ ثابت ہوتا ہو کہ رونے سے صحت پر کوئی مثبت اثرات مرتب ہوتے ہیں۔ مگر اس کے باوجود روایت یہی چلی آرہی ہے کہ رونا جذبات کی شدت کے باعث جسم میں پیدا ہونے والے زہریلے اثرات کا تریاق ہے۔ روٹنبرگ کہتے ہیں کہ رونا ایک طرح سے ہمارے جسم کی ورزش ہے جس کے ذریعے وہ دباؤ کی کیفیت سے باہر آنے کی کوشش کرتا ہے۔  ایک تجزیہ کار نے اس موضوع پر گزشتہ ایک سو چالیس برس کے اخبارات و رسائل میں چھپنے والے مضامین کا مطالعہ کرنے کے بعد یہ دریافت کیا کہ  فیصد لوگوں کا ماننا یہ تھا کہ رونا جسم و دماغ کے لیے اچھا ثابت ہوتا ہے جبکہ آنسو روک لینے یا پی جانے سے صحت پر برے اثرات مرتب ہوتے ہیں۔ روٹنبرگ اس تجزیئے کو صرف ایک زیب داستان سے تعبیر کرتے ہیں۔  اسی سلسلے میں ایک اور سوچ جو بہت بڑھا چڑھا کر پیش کی جاتی ہے وہ یہ کہ آنسو صرف غم کی کیفیت میں ہی نکلتے ہیں۔ اس بات کو جانچنے کے لیے تحقیق کاروں نے کچھ لوگوں کو ایک لیبارٹری میں ایک غم انگیز فلم دکھائی اور اس کے اختتام پر فوراً ان کے مزاج کو پرکھا گیا تو معلوم ہوا کہ جو لوگ فلم دیکھ کر نہیں روئے تھے ان کی نسبت رونے والے لوگ مزاجاً زیادہ برے حال میں تھے۔  دوسری طرف اس موضوع پر تحقیق کرنے والوں کو ایسے شواہد بھی ملے ہیں جو اس بات پر دلالت کرتے ہیں کہ جذباتی لمحوں میں رونا اچھا ہوتا ہے کیونکہ اس سے انسان کے اندر جمع ہونے والا غبار باہر نکل جاتا ہے۔ اس لیے کہا جاتا ہے کہ رو کر اپنے اندر کے غبار کو نکال باہر کرنا اس سے بہتر ہے کہ آنسوؤں کو پی کر اندر ہی اندر ان میں ڈوب جایا جائے۔ دوسری طرف جب ایڈونگرہوئٹس اور ان کے ساتھیوں نے لوگوں کو ایک غم انگیز فلم دکھا کر فوراً ان کے مزاجوں کا تجزیہ کرنے کی بجائے تقریباً ڈیڑھ گھنٹے کے وقفے کے بعد ان کے موڈز چیک کیے تو جو لوگ فلم دیکھنے کے دوران روئے تھے انہوں نے بتایا کہ وہ اپنے آپ کو فلم دیکھنے سے قبل کی نسبت اب جذباتی طور پر زیادہ تروتازہ محسوس کررہے تھے۔ ایڈونگر ہوئٹس وضاحت کرتے ہیں کہ جب ہم ایک بار رونے کے فوائد طے کرلیں گے تو یہ ایک مؤثر طریقہ ہوگا جس کے ذریعے ہم جذباتی کشمکش سے بحالی کی طرف آسکیں گے۔  رونے پر ہونے والی یہ تمام تحقیقات ابھی اپنے ابتدائی مراحل میں ہیں لیکن آنسوؤں کا اسرار اور اب ان کے متعلق ملنے والے نئے شواہد ان نظریات سے بہت زیادہ اہم ہیں جن پر سائنس دان ماضی میں یقین رکھتے تھے۔ محققین کو اس موضوع پر مزید تحقیق کرنے کی ضرورت ہے۔ ایڈونگرہوئٹس ہنستے ہوئے کہتے ہیں کہ اس بارے میں ڈارون کا نظریہ بالکل غلط تھا۔ آنسو انسانی فطرت سے عین مطابقت رکھتے ہیں۔ ہم اس لیے روتے ہیں کیونکہ ہمیں دوسرے لوگوں کی ضرورت ہوتی ہے۔ اسلام آباد ماہر ڈاکٹر قاسم محمد بٹر نے کہاکہ تقریباً فیصد مریض کینسرکی آخری سٹیج میں ہی آتے ہیں اوراس کی ایک وجہ آگاہی نہ ہوناہے۔ ',

In [ ]:
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,0,28,0_استعمال_رنز_گھر_دور,"[استعمال, رنز, گھر, دور, دنیا, قدیم, قبل, پہلے...",[ انہیں کھانے سے ذائقے کے ساتھ ساتھ خوشگواریت...
1,1,20,1_فلم_بالی_ووڈ_اداکارہ,"[فلم, بالی, ووڈ, اداکارہ, خان, میڈل, ساتھ, صفہ...",[ بالی ووڈ کے نامور اداکار رنویر سنگھ فلموں م...
2,2,18,2_ارب_ٹیکس_بینک_روپے,"[ارب, ٹیکس, بینک, روپے, لاکھ, کروڑ, مالی, او, ...",[ ارشاد انصاری اتوار اپريل بجٹ میں کئی اقد...
3,3,18,3_کینسر_منہ_ڈاکٹر_خون,"[کینسر, منہ, ڈاکٹر, خون, پاکستان, مریضوں, فالج...",[ فالج کا حملہ اس وقت ہوتا ہے جب دماغ کو خون ...
4,4,17,4_گیمز_سندھ_محمد_پاکستان,"[گیمز, سندھ, محمد, پاکستان, برانز, جی, سلور, گ...",[ پاکستان کو گذشتہ برس سری لنکا سے آخری ٹیسٹ...

In [ ]:
topic_model.get_document_info(documents)

,Document,Topic,Name,Representation,Representative_Docs,Top_n_words,Representative_document
0,بی آئی ایس پی نے بجٹ میں فیصد اضافہ مانگ لی...,2,2_ارب_ٹیکس_بینک_روپے,"[ارب, ٹیکس, بینک, روپے, لاکھ, کروڑ, مالی, او, ...",[ ارشاد انصاری اتوار اپريل بجٹ میں کئی اقد...,ارب - ٹیکس - بینک - روپے - لاکھ - کروڑ - مالی ...,False
1,پی ایس او کے مختلف اداروں پر واجبات ارب سے ت...,2,2_ارب_ٹیکس_بینک_روپے,"[ارب, ٹیکس, بینک, روپے, لاکھ, کروڑ, مالی, او, ...",[ ارشاد انصاری اتوار اپريل بجٹ میں کئی اقد...,ارب - ٹیکس - بینک - روپے - لاکھ - کروڑ - مالی ...,True
2,کراچی تھائی ایئر ویز انٹرنیشنل کے کنٹری مینیج...,2,2_ارب_ٹیکس_بینک_روپے,"[ارب, ٹیکس, بینک, روپے, لاکھ, کروڑ, مالی, او, ...",[ ارشاد انصاری اتوار اپريل بجٹ میں کئی اقد...,ارب - ٹیکس - بینک - روپے - لاکھ - کروڑ - مالی ...,False
3,اسلام آباد وفاقی حکومت کا قرضہ صرف ماہ میں ...,2,2_ارب_ٹیکس_بینک_روپے,"[ارب, ٹیکس, بینک, روپے, لاکھ, کروڑ, مالی, او, ...",[ ارشاد انصاری اتوار اپريل بجٹ میں کئی اقد...,ارب - ٹیکس - بینک - روپے - لاکھ - کروڑ - مالی ...,False
4,اسلام آباد وفاقی حکومت کی جانب سے اعلان کردہ...,2,2_ارب_ٹیکس_بینک_روپے,"[ارب, ٹیکس, بینک, روپے, لاکھ, کروڑ, مالی, او, ...",[ ارشاد انصاری اتوار اپريل بجٹ میں کئی اقد...,ارب - ٹیکس - بینک - روپے - لاکھ - کروڑ - مالی ...,False
...,...,...,...,...,...,...,...
96,ایسیکس کی رہائشی ٹورز رینلڈز نے بتایا کہ وہ ...,0,0_استعمال_رنز_گھر_دور,"[استعمال, رنز, گھر, دور, دنیا, قدیم, قبل, پہلے...",[ انہیں کھانے سے ذائقے کے ساتھ ساتھ خوشگواریت...,استعمال - رنز - گھر - دور - دنیا - قدیم - قبل ...,False
97,زیر نظر مضمون میں یہ کوشش کی گئی ہے کہ ان چی...,0,0_استعمال_رنز_گھر_دور,"[استعمال, رنز, گھر, دور, دنیا, قدیم, قبل, پہلے...",[ انہیں کھانے سے ذائقے کے ساتھ ساتھ خوشگواریت...,استعمال - رنز - گھر - دور - دنیا - قدیم - قبل ...,True
98,غیر ملکی خبر رساں ادارے کے مطابق مصر کے شہر ...,0,0_استعمال_رنز_گھر_دور,"[استعمال, رنز, گھر, دور, دنیا, قدیم, قبل, پہلے...",[ انہیں کھانے سے ذائقے کے ساتھ ساتھ خوشگواریت...,استعمال - رنز - گھر - دور - دنیا - قدیم - قبل ...,False
99,مقامی میڈیا کے مطابق ری لیو ء میں ترکی پہنچا...,0,0_استعمال_رنز_گھر_دور,"[استعمال, رنز, گھر, دور, دنیا, قدیم, قبل, پہلے...",[ انہیں کھانے سے ذائقے کے ساتھ ساتھ خوشگواریت...,استعمال - رنز - گھر - دور - دنیا - قدیم - قبل ...,False
100,جاؤ یپینگ نامی چینی کسان نے ء میں اپنا تین ...,0,0_استعمال_رنز_گھر_دور,"[استعمال, رنز, گھر, دور, دنیا, قدیم, قبل, پہلے...",[ انہیں کھانے سے ذائقے کے ساتھ ساتھ خوشگواریت...,استعمال - رنز - گھر - دور - دنیا - قدیم - قبل ...,False

In [ ]:
topic_distr, _ = topic_model.approximate_distribution(documents, window=3, min_similarity=0.01)

In [ ]:
print(topic_distr)

[[0.11043388 0.08970342 0.53260223 0.13086717 0.13639329]
 [0.12836009 0.07468817 0.55017893 0.11840401 0.1283688 ]
 [0.12226354 0.15802625 0.45874011 0.10914482 0.15182527]
 [0.11350355 0.09710731 0.52281194 0.13312146 0.13345574]
 [0.10493059 0.05386726 0.60581182 0.13426541 0.10112492]
 [0.13159524 0.11004025 0.49889632 0.09800484 0.16146335]
 [0.09199096 0.06750497 0.59979011 0.08452141 0.15619256]
 [0.12985309 0.05334421 0.6193659  0.06490294 0.13253386]
 [0.13596989 0.07979552 0.51870151 0.14502809 0.12050499]
 [0.40403018 0.10713312 0.17364689 0.18921167 0.12597814]
 [0.10066036 0.06244056 0.59158469 0.1129148  0.13239958]
 [0.12487921 0.08441333 0.54817729 0.12823979 0.11429038]
 [0.31535548 0.0906678  0.27743639 0.15465104 0.16188929]
 [0.13400239 0.08995014 0.23627803 0.12649631 0.41327314]
 [0.35268588 0.08981247 0.29507203 0.11102903 0.15140059]
 [0.12137293 0.09856914 0.48123156 0.15257746 0.1462489 ]
 [0.10989163 0.09765875 0.19682453 0.16591337 0.42971173]
 [0.11799234 0.07903903 0.45831827 0.22238126 0.12226911]
 [0.13632931 0.08479284 0.51954365 0.14080147 0.11853273]
 [0.07027857 0.15394438 0.55890408 0.06217102 0.15470195]
 [0.13574093 0.31641993 0.33703817 0.09080558 0.11999539]
 [0.3617114  0.31648735 0.0862857  0.11764819 0.11786735]
 [0.12950619 0.55430281 0.083872   0.11966224 0.11265676]
 [0.13041292 0.56674366 0.09086896 0.11292891 0.09904555]
 [0.16517302 0.40743906 0.12374558 0.15004931 0.15359303]
 [0.13678867 0.55020339 0.12586355 0.09116901 0.09597538]
 [0.13876179 0.49038893 0.1065351  0.12809601 0.13621816]
 [0.14208285 0.55880729 0.06558124 0.11558363 0.11794499]
 [0.14878285 0.40713369 0.10485371 0.17977954 0.15945021]
 [0.18267424 0.60080303 0.04773066 0.08496    0.08383207]
 [0.13886064 0.48219275 0.11037048 0.12660765 0.14196848]
 [0.15666749 0.51970988 0.11452213 0.08048736 0.12861314]
 [0.14481402 0.45688335 0.08820261 0.12424962 0.18585041]
 [0.13132674 0.47124743 0.14699277 0.09340517 0.15702789]
 [0.17996828 0.47375307 0.10250299 0.13419816 0.1095775 ]
 [0.25662581 0.25999408 0.1572046  0.16307656 0.16309895]
 [0.16338107 0.45840928 0.09120191 0.13428793 0.15271982]
 [0.14389664 0.54074947 0.10050392 0.10696145 0.10788853]
 [0.13802882 0.48025133 0.14525793 0.10684437 0.12961756]
 [0.15169575 0.52124701 0.10652506 0.11168245 0.10884973]
 [0.13037972 0.45376821 0.16806142 0.11272749 0.13506316]
 [0.42454162 0.10623379 0.11085537 0.22921217 0.12915705]
 [0.16323708 0.09098965 0.12133374 0.50193393 0.1225056 ]
 [0.19780141 0.13836344 0.14678306 0.34978399 0.16726809]
 [0.14727672 0.11099118 0.15448104 0.43850673 0.14874433]
 [0.17840808 0.1203279  0.1199978  0.47375553 0.10751069]
 [0.15402763 0.08761134 0.14002531 0.50527868 0.11305705]
 [0.48142244 0.10453474 0.07960172 0.23346506 0.10097604]
 [0.42846074 0.14922826 0.10013259 0.21270735 0.10947106]
 [0.1993164  0.14883051 0.10878663 0.44352177 0.09954469]
 [0.43330374 0.09072306 0.09297584 0.2723767  0.11062065]
 [0.2157079  0.08315348 0.09364626 0.53727372 0.07021863]
 [0.22175935 0.11766528 0.15591622 0.4126146  0.09204455]
 [0.44599754 0.10013395 0.09051784 0.26021446 0.10313621]
 [0.21510489 0.09299203 0.08482598 0.51804646 0.08903064]
 [0.41482572 0.12185676 0.10112332 0.24629483 0.11589937]
 [0.18534642 0.11432808 0.09020375 0.49096168 0.11916007]
 [0.21261997 0.11080054 0.12125374 0.47267498 0.08265076]
 [0.17601292 0.0970784  0.12735107 0.48875384 0.11080377]
 [0.22783631 0.08515131 0.08483625 0.51083292 0.09134321]
 [0.18116748 0.10974561 0.11267684 0.48715833 0.10925175]
 [0.12778192 0.40014252 0.07205235 0.10543722 0.29458599]
 [0.11320077 0.21071294 0.10216489 0.11751956 0.45640184]
 [0.16463906 0.1014812  0.10675917 0.10640603 0.52071453]
 [0.15189319 0.13432665 0.08466878 0.15110118 0.4780102 ]
 [0.0982821  0.41972798 0.1077586  0.14418442 0.2300469 ]
 [0.1032039  0.16741514 0.09373189 0.18151864 0.45413043]
 [0.12026276 0.1643846  0.10357838 0.33640623 0.27536803]
 [0.10774424 0.13260679 0.18046867 0.15025974 0.42892057]
 [0.13351139 0.13425568 0.15633586 0.13640916 0.43948791]
 [0.3159892  0.21051631 0.0903291  0.11521924 0.26794615]
 [0.10654554 0.21308887 0.10562184 0.07412931 0.50061444]
 [0.14624988 0.1478312  0.11298989 0.15086959 0.44205942]
 [0.13343801 0.16714153 0.0890391  0.16245016 0.4479312 ]
 [0.29600406 0.15420838 0.12302157 0.16747701 0.25928898]
 [0.12384362 0.17111104 0.09236842 0.18186009 0.43081684]
 [0.13385508 0.15215688 0.11583848 0.14361495 0.4545346 ]
 [0.10942994 0.13637927 0.11458395 0.1631022  0.47650465]
 [0.15599641 0.14185256 0.1413405  0.16005936 0.40075116]
 [0.11011986 0.16172459 0.18497048 0.11890145 0.42428362]
 [0.12051183 0.22164887 0.09018073 0.14386324 0.42379532]
 [0.3564359  0.21235102 0.14400995 0.16228677 0.12491636]
 [0.2302252  0.1609289  0.07883133 0.40505915 0.12495542]
 [0.36458406 0.17531606 0.12040203 0.22075943 0.11893843]
 [0.42722545 0.21268673 0.10736204 0.1362364  0.11648937]
 [0.19789204 0.09968837 0.08995266 0.53363033 0.07883661]
 [0.22097541 0.12807654 0.09388082 0.43391966 0.12314756]
 [0.42830671 0.09957734 0.16678601 0.20563    0.09969994]
 [0.40248718 0.17757405 0.15644988 0.1642522  0.09923669]
 [0.3487842  0.16325947 0.11423363 0.24715881 0.12656389]
 [0.41635951 0.13668649 0.15475661 0.1624038  0.1297936 ]
 [0.39989919 0.13629935 0.11360376 0.20783779 0.14235992]
 [0.28276221 0.13364237 0.204627   0.22865254 0.15031588]
 [0.47204018 0.11422577 0.13519501 0.18514046 0.09339858]
 [0.16007013 0.13892079 0.45387111 0.13155347 0.1155845 ]
 [0.15931906 0.13177709 0.39578581 0.17109135 0.14202668]
 [0.41447646 0.16358666 0.11470031 0.1725065  0.13473008]
 [0.47130794 0.13009857 0.10943838 0.18254376 0.10661134]
 [0.37703085 0.15708599 0.14888375 0.17765401 0.13934539]
 [0.3614616  0.17734181 0.1967783  0.13375854 0.13065976]
 [0.4339943  0.11409892 0.16702536 0.14031359 0.14456783]]

In [ ]:
topic_model.visualize_distribution(topic_distr[0], width=600,height=600,  title="Topic Probability Distribution (UDC)")

# Evaluation
we used three evaluation metrics to compare the results.

1. The coherence score is used to capture the degree of similarity between the words within each topic, with higher scores indicating more coherent topics. We used two coherence metrics NPMI and Cv Score.
2. IRBO measures are used to assess how different and distinct the topics are in a topic model.

### Coherence Score
To evaluate the model topics coherence we use [Gensim](https://radimrehurek.com/gensim/models/coherencemodel.html) library

In [ ]:
texts = [[word for word in str(document).split() if word not in stopwords_ur] for document in documents]
id2word = corpora.Dictionary(texts)
corpus = [id2word.doc2bow(text) for text in texts]

In [ ]:
topics_bert=[]
for i in topic_model.get_topics():
  row=[]
  topic= topic_model.get_topic(i)
  for word in topic:
     row.append(word[0])
  topics_bert.append(row)

In [ ]:
print(topics_bert)

[['کینسر', 'استعمال', 'جسم', 'علاج', 'افراد', 'پانی', 'ماہرین', 'صحت', 'خواتین', 'تحقیق'], ['ٹیم', 'کرکٹ', 'محمد', 'میڈل', 'انگلینڈ', 'گولڈ', 'ٹیسٹ', 'میچ', 'کھلاڑیوں', 'گیمز'], ['روپے', 'ارب', 'فیصد', 'ٹیکس', 'حکومت', 'پاکستان', 'بجٹ', 'ڈالر', 'کروڑ', 'مالی'], ['فلم', 'خان', 'ووڈ', 'بالی', 'اداکارہ', 'سلمان', 'بھارتی', 'اداکار', 'میڈیا', 'انڈسٹری'], ['ظفر', 'میشا', 'شفیع', 'علی', 'جنسی', 'ہراسانی', 'الزام', 'گلوکارہ', 'مومنہ', 'ہراساں']]

In [ ]:
# compute Coherence Score

cm = CoherenceModel(topics=topics_bert, texts=texts, dictionary=id2word, coherence='c_npmi')
coherence = round(cm.get_coherence(),2)
print('\nCoherence Score: ', coherence)

Coherence Score:  -0.08

**Diversity Score**

In [ ]:
import itertools
from rbo import rbo
import numpy as np

class InvertedRBO:
    def __init__(self):
        pass

    def irbo(self, topics, topk=10, weight=0.9):
        """
        Calculate inverted Rank Biased Overlap (RBO) as a measure of topic diversity from a list of lists of words.

        :param topics: A list of lists of words representing different topics.
        :param topk: The number of top words on which RBO will be computed.
        :param weight: Weight of each agreement at depth d: p**(d-1). When set to 1.0, there is no weight,
                       and the RBO returns to average overlap.
        :return: The inverted RBO topic diversity score.
        """
        if topk <= 0:
            raise ValueError("topk must be a positive integer.")

        num_topics = len(topics)
        if num_topics == 0:
            raise ValueError("topics list cannot be empty.")

        if topk > len(topics[0]):
            raise Exception('Words in topics are less than topk')

        collect = []
        for list1, list2 in itertools.combinations(topics, 2):
            rbo_val = rbo(list1[:topk], list2[:topk], p=weight)[2]
            collect.append(rbo_val)

        Irbo_score = 1 - np.mean(collect)
        return Irbo_score

In [ ]:
inverted_rbo_calculator = InvertedRBO()
IRBO= round(inverted_rbo_calculator.irbo(topics_bert, topk=10, weight=0.9),2)
print("Inverted RBO Score:", IRBO)

Inverted RBO Score: 0.99

# Visualize Topics

In [ ]:
topic_model.visualize_topics()

In [ ]:
topic_model.visualize_barchart(n_words=10, width=220, height=270, title= "Topic Word Scores (UDC)")