In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np
import re

In [ ]:
#Load Clean UNTM Dataset from drive
df = pd.read_csv('/content/drive/MyDrive/Clean_BigCorpus.csv', encoding='utf-8')

In [ ]:
df.head()

,Document,Category,Clean_Data
0,﻿اسلام آباد: ایسوسی ایشن آف چارٹرڈ سرٹیفائی...,Business,اسلام آباد ایسوسی ایشن آف چارٹرڈ سرٹیفائیڈا...
1,اسلام آباد: ایف بی آرنے 1 ارب30کروڑ روپے سے ...,Business,اسلام آباد ایف بی آرنے اربکروڑ روپے سے زائد...
2,کراچی: بزنس مین گروپ کے چیئرمین اور کراچی چیم...,Business,کراچی بزنس مین گروپ کے چیئرمین اور کراچی چیمب...
3,کراچی: ٹرانسپورٹ اور پٹرولیم مصنوعات کی درآم...,Business,کراچی ٹرانسپورٹ اور پٹرولیم مصنوعات کی درآمد...
4,بجٹ کی آمد آمد ہے۔ ایکسپریس میڈیا گروپ کی ی...,Business,بجٹ کی آمد آمد ہے۔ ایکسپریس میڈیا گروپ کی ی...

In [ ]:
actual_Label = df['Category'].tolist()

In [ ]:
print(len(actual_Label))

1008

In [ ]:
df=df.drop(columns=['Document', 'Category'])

In [ ]:
df.head()

                                          Clean_Data
0   اسلام آباد  ایسوسی ایشن آف چارٹرڈ سرٹیفائیڈا...
1   اسلام آباد ایف بی آرنے  اربکروڑ روپے سے زائد...
2   کراچی بزنس مین گروپ کے چیئرمین اور کراچی چیمب...
3   کراچی ٹرانسپورٹ اور پٹرولیم مصنوعات کی درآمد...
4   بجٹ کی آمد آمد ہے۔ ایکسپریس میڈیا گروپ کی ی...

In [ ]:
# # Assign split percentages
train_percent = 0.8
val_percent = 0.1

# Determine the split for each row
total_rows = len(df)
train_rows = int(train_percent * total_rows)
val_rows = int(val_percent * total_rows)

# Create the 'Split' column and assign split labels
split_labels = ['train'] * train_rows + ['val'] * val_rows + ['test'] * (total_rows - train_rows - val_rows)
np.random.shuffle(split_labels)  # Shuffle the labels randomly

df['Split'] = split_labels

df.head()

                                          Clean_Data  Split
0   اسلام آباد  ایسوسی ایشن آف چارٹرڈ سرٹیفائیڈا...  train
1   اسلام آباد ایف بی آرنے  اربکروڑ روپے سے زائد...    val
2   کراچی بزنس مین گروپ کے چیئرمین اور کراچی چیمب...  train
3   کراچی ٹرانسپورٹ اور پٹرولیم مصنوعات کی درآمد...  train
4   بجٹ کی آمد آمد ہے۔ ایکسپریس میڈیا گروپ کی ی...  train

In [ ]:
df['Label'] = actual_Label
df.head()

                                          Clean_Data  Split     Label
0   اسلام آباد  ایسوسی ایشن آف چارٹرڈ سرٹیفائیڈا...  train  Business
1   اسلام آباد ایف بی آرنے  اربکروڑ روپے سے زائد...    val  Business
2   کراچی بزنس مین گروپ کے چیئرمین اور کراچی چیمب...  train  Business
3   کراچی ٹرانسپورٹ اور پٹرولیم مصنوعات کی درآمد...  train  Business
4   بجٹ کی آمد آمد ہے۔ ایکسپریس میڈیا گروپ کی ی...  train  Business

In [ ]:
def remove_nonbreaking_space(text):
    return re.sub(r'\xa0', ' ', text)

df['Clean_Data'] = df['Clean_Data'].apply(remove_nonbreaking_space)

In [ ]:
for document in df['Clean_Data'].iloc[:2]:
    print(document)
    print('---')

 اسلام آباد  ایسوسی ایشن آف چارٹرڈ سرٹیفائیڈاکاؤئنٹنٹس  نے کہا ہے کہ ہمارے ٹیکس نظام کی سنجیدگی سے جانچ پڑتال کی ضرورت ہے ٹیکس دہندگان اور عوام کا ٹیکس حکام پر اعتماد انتہائی کم ہے جس کے نتیجے میں ٹیکس چوری کے باعث قومی خزانہ کو اربوں روپے کا نقصان ہو رہا ہے   اے سی سی اے کی جانب سے جمع کرائی گئی ٹیکس تجاویز میں ٹیکس کی شرح کو کم کر کے یک ہندسی کرنے ڈائریکٹ ٹیکسیشن کی رفتار میں اضافے نادرا ڈیٹا بیس اور ودہولڈنگ ٹیکس ڈیٹا کے استعمال اور اثاثہ جات کی تشخیص شامل ہیں۔ اے سی سی اے کی اسٹرکچرل ریفارمز میں ٹیکس دہندہ کے تمام ٹیکس امور کیلیے ایک ٹیکس ریٹرن تجویز کیاگیا ہے   تجاویز میں کہاگیا کہ پاکستان کی ٹیکس ٹو جی ڈی پی شرح خطے میں سب سے کم مگر کارپوریٹ ٹیکس کی شرح  فیصد کی بلند سطح پر ہے ٹیکس حکام کو اسے کم کرنے کی ضرورت ہے سیلز ٹیکس بھی خطے میں انتہائی بلند یعنی  فیصد ہے جو  ایشیا میں اوسطاً  فیصد کے قریب ہے سیلز ٹیکس بھی کم  اور براہ راست ٹیکس کے متبادل کے بجائے ٹیکس بیس کی توسیع کیلیے استعمال کیا جانا چاہیے۔
---
 اسلام آباد ایف بی آرنے  اربکروڑ روپے سے زائد مالیت کے گڈز ڈکلیئریشن فنڈ کے استعمال کیلیے خصوصی سیکریٹریٹ قائم کرنے اور ایف بی آر ہیڈ کوارٹرز اورکسٹمز ہاؤس کراچی میں قائم ڈیٹا سینٹرزکی اپ گریڈیشن کرنے کا فیصلہ کیا ہے۔  ایکسپریس کو دستیاب دستاویزکے مطابق یہ اہم فیصلے ایف بی آرکے ممبر کسٹمز زاہدکھوکھرکی زیرصدارت اجلاس میں کیے گئے جس میں یہ بھی فیصلہ کیا گیا کہ کسٹمزکراچی کے وی بوک اوراس کے نیٹ ورک ڈیٹا سینٹر کی فعالیت کو برقرار رکھنے کے لیے پاکستان ریونیو آٹومیشن لمیٹڈ کی جانب سے ضرورت کے مطابق بروقت پروکیورمنٹس کو بھی یقینی بنایا جائے گا تاکہ آئندہ کسٹمز کراچی کے وی بوک نیٹ ورک ڈیٹا سینٹر میں بریک ڈاون کی صورتحال سے بچا جا سکے۔  اجلاس میں یہ بھی فیصلہ کیا گیا کہ اربکروڑ روپے سے زائد مالیت کے گڈز ڈکلیئریشن فنڈ کے استعمال کے لیے خصوصی سیکریٹریٹ قائم کیا جائے گا اور یہ سیکریٹریٹ دسمبر کو جاری کردہ کسٹمز جنرل آرڈر نمبر کے مطابق جی ڈی فنڈ کو استعمال میں لائے گا۔ اس بارے میں ایف بی آر حکام کا کہنا ہے کہ ایف بی آر نے  میں درآمدی کنسائنمنٹس کی پروسیسنگ پر  روپے فی کنسائنمنٹ کے حساب سے گڈز ڈکلیئریشن پروسیسنگ فیس عائد کی تھی جس کی مد میں اب تک ایف بی آر کو اربکروڑ روپے سے زائد کا ریونیو حاصل ہوچکا ہے جو گڈز ڈکلیئریشن فنڈ میں موجود ہے جسے اب استعمال کرنے کا فیصلہ کیا ہے۔  ذرائع کے مطابق  ہفتے قبل کسٹمز ہاؤس کراچی کے وی بوک نیٹ ورک ڈیٹا سینٹر میں بریک ڈاؤن سے کنسائنمنٹس کی کلیئرنس میں بڑے پیمانے پر خلل پیدا ہوا اور اس صورتحال سے نمٹنے کے لیے  اپریل کو ہنگامی ویڈیوکانفرنس کال کی گئی جس میں صورتحال کا تفصیلی جائزہ لیا گیا اس کانفرنس میںاس بریک ڈاؤن پر قابو پانے اور فوری انتظامات کے لیے ایف بی آر سے فوری طور پر  ہزار ڈالرفراہم کرنے کی درخواست کی گئی تاکہ وی باکس آپریشنز جاری رکھے جا سکیں اورکنسائنمنٹس کی بروقت کلیئرنس کو یقینی بنایا جاسکے۔  دستاویز کے مطابق ایف بی آرکے ممبر آئی ٹی اور چیف ایگزیکٹو آفیسر پرال کو بورڈ ان کونسل کے فیصلے کے مطابق ڈیٹا سینٹرز کی فوری گریڈیشن اور وی بوک اوراسکے نیٹ ورک ڈیٹا سینٹر کی فعالیت کو برقرار رکھنے کے لیے بروقت پروکیورمنٹس یقینی بنانے کی ذمے داری سونپی گئی۔
---

In [ ]:
import nltk
stopwords=pd.read_csv('/content/drive/MyDrive/stopwords.txt',names=['List'])
# stopwords['List']

stopwords_ur=[]
for li in stopwords['List']:
  stopwords_ur.append(li)
print(len(stopwords_ur))
print(stopwords_ur)

401
['کی', 'ہیں', 'ہے', 'رہا', 'رہی', 'رہے', 'تھا', 'تھے', 'تھی', 'تھى', 'میں', 'کہ', 'کے', 'ہوتے', 'کہہ', 'بنانا', 'پھر', 'لکین', 'ہوتی', 'لیتی', 'ایسی', 'ائے', 'ہوئے', 'ہوۓ ', 'مگر', 'چاہے', 'کیے', 'تاکہ', 'تم', 'آکر', 'لگا', 'ہوگیئں', 'ليے', 'رہتی', 'ہوگئی', 'انھوں', 'چاہتے', 'پاگیئں', 'آنا', 'کروا', 'رکھ', 'آتی', 'یہاں', 'جیسا', 'چکے', 'کرئے', 'دیے', 'چکا', 'ملتا', 'کبھی', 'ایسا', 'کرسکیں', 'ہوسکے', 'سکیں', 'لہذا', 'چاہئے', 'وہیں', 'اٹھایا', 'جہنوں', 'ہمارے', 'لیے', 'آرہے', 'کرگیئں', 'بنانے', 'سکتا', 'وغیرہ', 'دے', 'ہوۓ', 'رہنے', 'ہوۓ', 'کئے', 'لگے', 'لگایا', 'لائے', 'کہے', 'کرے', 'رہئں', 'آگئے', 'کئی', 'کم', 'ملی', 'جنہیں', 'ہوئیں', 'تھیں', 'ابھی', 'پاگئیں', 'آئے', 'کرا', 'دیا', 'جہاں', 'آگئیں', 'کرتی', 'رہیں', 'کرتیں', 'دیتی', 'ہوگئے', 'ديتے', 'انہں', 'ایسے', 'رکھتے', 'رہتے', 'رکھی', 'کیں', 'كیا', 'وه', 'جنہيں', 'کروائی', 'دینا', 'جسے', 'جاتی', 'اسکی', 'ملے', 'کرگئى', 'جن', 'آپکو', 'جنہوں', 'دیئے', 'والی', 'جبکہ', 'دیگر', 'آپکا', 'رکھنے', 'انہىں', 'کيے', 'یعنی', 'كيے', 'بننے', 'جاملے', 'ليكن', 'كرنے', 'كر', 'آيا', 'كرگئى', 'پھر', 'کچھ', 'آتے', 'دینے', 'اپ', 'ہونا', 'انہیں', 'لگی', 'آنے', 'کرلی', 'ہوگئى', 'پایا', 'آپکے', 'بنائی', 'کرديا', 'لا', 'رکهنے', 'كہ', 'بنا', 'كرديا', 'ركھى', 'ميں', 'ركھتے', 'كروائى', 'حتی', 'لایا', 'لیتے', 'ہمیں', 'گئى', 'بنائے', 'تاہم', 'پھر بھی', 'بنايا', 'دىے', 'ايم اے او', 'كئى', 'پڑا', 'رکھے', 'انہی', 'دیں', 'ليکر', 'البتہ', 'ہى', 'کرکے', 'پائی', 'لینا', 'دہی', 'دئیے', 'گوکہ', 'دئيے', 'كيں', 'جایا', 'کروایا', 'كیے', 'ہاں', 'کہنا', 'کیلئے', 'ہوگا', 'دیکھتے', 'آرہے', 'آگیا', 'اپنے آپ', 'طرف سے', 'ملا', 'آپكى', 'پھر بھی', 'كرگئے', 'آپکی', 'ليا', 'ديے', 'كے', 'رکھى', 'رکھتا', 'کرايا', 'چلے', 'آتا', 'لاکر', 'جیسے', 'کرليا', 'کیا ہے', 'وہاں', 'لینے', 'پاگئے', 'ہر', 'رکھنا', 'كيا', 'آیا', 'هے', 'كى', 'کرایا', 'حاصل', 'آگئى', 'دى', 'کبهی', 'جاسكتا', 'اسى', 'كی', 'كہا', 'كرو', 'اور', 'سے', 'کا', 'کى', 'سب', 'کو', 'كو', 'نے', 'اس', 'ہيں', 'پر', 'کر', 'ايک', 'كا', 'ہو', 'بهی', 'ایک', 'یہ', 'نہيں', 'ان', 'کيا', 'تو', 'وہ', 'لئے', 'کرنے', 'آپ', 'کہا', 'گيا', 'جو', 'گا', 'ہی', 'جائے', 'نہ', 'جب', 'اپنے', 'جس', 'دیا', 'ہوئے', 'تک', 'بعد', 'انہوں', 'رہے', 'ليکن', 'گی', 'کریں', 'گے', 'کرتے', 'ہونے', 'گئے', 'اپنی', 'والے', 'بہت', 'کسی', 'جا', 'تهی', 'یا', 'گئی', 'ہم', 'ہوں', 'کيلئے', 'زیادہ', 'رہا', 'طرح', 'اگر', 'اب', 'ہوا', 'دی', 'ہوتا', 'کام', 'جب', 'جو', 'گا', 'لیکن ', 'کرتى ', 'کرگئی ', 'گیا ', 'اسی', 'کیا', 'ہوئی', 'انہيں', 'جانا', 'جانے ', 'ہوئی ', 'کرگئے ', 'دیا', 'کو ', 'میں', 'ہوئے', 'ایک', 'تھے ', 'آپ ', 'نہیں', 'لیکن', 'تھی', 'جو', 'اور', 'کرتى', 'کرتا', 'کرگئی', 'کر', 'جاتے', 'لئے', 'گیا', 'کہا ', 'جاتا', 'اس ', 'جاتى', 'کرنا', 'کسی', 'بھی', 'طرف', 'ہوتا', 'لیکن', 'یہ', 'ہی', 'یا', 'اگرچہ', 'کہ', 'نے', 'رکھو', 'کرو', 'جانے', 'انہيں ', 'ديا', 'سے', 'کرگئے', 'پر', 'ہوئى', 'ان', 'اپنى', 'اپنا', 'ذریعے', 'رکھا', 'ہونے', 'اپنے', 'بعد', 'پاگئى', 'دیتے', 'كرتے', 'ہوتى', 'کہتے', 'دی', 'کرگئیں', 'اسے', 'اسی', 'لیا', 'لے', 'لی', 'کس', 'کسی', 'لیے', 'آئی', 'بنے', 'کچھ ', 'ہی', 'کرتی', 'کرتا', 'لئے', 'طور', 'نہیں', 'بلکہ', 'کیونکہ', 'کیوں', 'جس ', 'گئی', 'ہونے', 'وجہ', 'ہوگیا', 'لينے']

In [ ]:
def remove_stopwords(text: str, stopwords_ur):
    return " ".join(word for word in text.split() if word not in stopwords_ur)

In [ ]:
df['Clean_Data'] = df['Clean_Data'].apply(lambda text: remove_stopwords(text, stopwords_ur))

In [ ]:
for document in df['Clean_Data'].iloc[:2]:
    print(document)
    print('---')

اسلام آباد ایسوسی ایشن آف چارٹرڈ سرٹیفائیڈاکاؤئنٹنٹس ٹیکس نظام سنجیدگی جانچ پڑتال ضرورت ٹیکس دہندگان عوام ٹیکس حکام اعتماد انتہائی نتیجے ٹیکس چوری باعث قومی خزانہ اربوں روپے نقصان اے سی سی اے جانب جمع کرائی ٹیکس تجاویز ٹیکس شرح یک ہندسی ڈائریکٹ ٹیکسیشن رفتار اضافے نادرا ڈیٹا بیس ودہولڈنگ ٹیکس ڈیٹا استعمال اثاثہ جات تشخیص شامل ہیں۔ اے سی سی اے اسٹرکچرل ریفارمز ٹیکس دہندہ تمام ٹیکس امور کیلیے ٹیکس ریٹرن تجویز کیاگیا تجاویز کہاگیا پاکستان ٹیکس ٹو جی ڈی پی شرح خطے کارپوریٹ ٹیکس شرح فیصد بلند سطح ٹیکس حکام ضرورت سیلز ٹیکس خطے انتہائی بلند فیصد ایشیا اوسطاً فیصد قریب سیلز ٹیکس براہ راست ٹیکس متبادل بجائے ٹیکس بیس توسیع کیلیے استعمال چاہیے۔
---
اسلام آباد ایف بی آرنے اربکروڑ روپے زائد مالیت گڈز ڈکلیئریشن فنڈ استعمال کیلیے خصوصی سیکریٹریٹ قائم ایف بی آر ہیڈ کوارٹرز اورکسٹمز ہاؤس کراچی قائم ڈیٹا سینٹرزکی گریڈیشن فیصلہ ہے۔ ایکسپریس دستیاب دستاویزکے مطابق اہم فیصلے ایف بی آرکے ممبر کسٹمز زاہدکھوکھرکی زیرصدارت اجلاس فیصلہ کسٹمزکراچی وی بوک اوراس نیٹ ورک ڈیٹا سینٹر فعالیت برقرار پاکستان ریونیو آٹومیشن لمیٹڈ جانب ضرورت مطابق بروقت پروکیورمنٹس یقینی بنایا آئندہ کسٹمز کراچی وی بوک نیٹ ورک ڈیٹا سینٹر بریک ڈاون صورتحال بچا سکے۔ اجلاس فیصلہ اربکروڑ روپے زائد مالیت گڈز ڈکلیئریشن فنڈ استعمال خصوصی سیکریٹریٹ قائم سیکریٹریٹ دسمبر جاری کردہ کسٹمز جنرل آرڈر نمبر مطابق جی ڈی فنڈ استعمال گا۔ بارے ایف بی آر حکام ایف بی آر درآمدی کنسائنمنٹس پروسیسنگ روپے فی کنسائنمنٹ حساب گڈز ڈکلیئریشن پروسیسنگ فیس عائد مد ایف بی آر اربکروڑ روپے زائد ریونیو ہوچکا گڈز ڈکلیئریشن فنڈ موجود استعمال فیصلہ ہے۔ ذرائع مطابق ہفتے قبل کسٹمز ہاؤس کراچی وی بوک نیٹ ورک ڈیٹا سینٹر بریک ڈاؤن کنسائنمنٹس کلیئرنس بڑے پیمانے خلل پیدا صورتحال نمٹنے اپریل ہنگامی ویڈیوکانفرنس کال صورتحال تفصیلی جائزہ کانفرنس میںاس بریک ڈاؤن قابو پانے فوری انتظامات ایف بی آر فوری ہزار ڈالرفراہم درخواست وی باکس آپریشنز جاری اورکنسائنمنٹس بروقت کلیئرنس یقینی بنایا جاسکے۔ دستاویز مطابق ایف بی آرکے ممبر آئی ٹی چیف ایگزیکٹو آفیسر پرال بورڈ کونسل فیصلے مطابق ڈیٹا سینٹرز فوری گریڈیشن وی بوک اوراسکے نیٹ ورک ڈیٹا سینٹر فعالیت برقرار بروقت پروکیورمنٹس یقینی ذمے داری سونپی گئی۔
---

In [ ]:
df.to_csv('corpus.tsv', sep='\t', header=False, index=False,  encoding='utf-8')

In [ ]:
df = pd.read_csv("corpus.tsv", sep='\t', header=None)

In [ ]:
documents = df[0].values.tolist()
print((documents[1]))

اسلام آباد ایف بی آرنے اربکروڑ روپے زائد مالیت گڈز ڈکلیئریشن فنڈ استعمال کیلیے خصوصی سیکریٹریٹ قائم ایف بی آر ہیڈ کوارٹرز اورکسٹمز ہاؤس کراچی قائم ڈیٹا سینٹرزکی گریڈیشن فیصلہ ہے۔ ایکسپریس دستیاب دستاویزکے مطابق اہم فیصلے ایف بی آرکے ممبر کسٹمز زاہدکھوکھرکی زیرصدارت اجلاس فیصلہ کسٹمزکراچی وی بوک اوراس نیٹ ورک ڈیٹا سینٹر فعالیت برقرار پاکستان ریونیو آٹومیشن لمیٹڈ جانب ضرورت مطابق بروقت پروکیورمنٹس یقینی بنایا آئندہ کسٹمز کراچی وی بوک نیٹ ورک ڈیٹا سینٹر بریک ڈاون صورتحال بچا سکے۔ اجلاس فیصلہ اربکروڑ روپے زائد مالیت گڈز ڈکلیئریشن فنڈ استعمال خصوصی سیکریٹریٹ قائم سیکریٹریٹ دسمبر جاری کردہ کسٹمز جنرل آرڈر نمبر مطابق جی ڈی فنڈ استعمال گا۔ بارے ایف بی آر حکام ایف بی آر درآمدی کنسائنمنٹس پروسیسنگ روپے فی کنسائنمنٹ حساب گڈز ڈکلیئریشن پروسیسنگ فیس عائد مد ایف بی آر اربکروڑ روپے زائد ریونیو ہوچکا گڈز ڈکلیئریشن فنڈ موجود استعمال فیصلہ ہے۔ ذرائع مطابق ہفتے قبل کسٹمز ہاؤس کراچی وی بوک نیٹ ورک ڈیٹا سینٹر بریک ڈاؤن کنسائنمنٹس کلیئرنس بڑے پیمانے خلل پیدا صورتحال نمٹنے اپریل ہنگامی ویڈیوکانفرنس کال صورتحال تفصیلی جائزہ کانفرنس میںاس بریک ڈاؤن قابو پانے فوری انتظامات ایف بی آر فوری ہزار ڈالرفراہم درخواست وی باکس آپریشنز جاری اورکنسائنمنٹس بروقت کلیئرنس یقینی بنایا جاسکے۔ دستاویز مطابق ایف بی آرکے ممبر آئی ٹی چیف ایگزیکٹو آفیسر پرال بورڈ کونسل فیصلے مطابق ڈیٹا سینٹرز فوری گریڈیشن وی بوک اوراسکے نیٹ ورک ڈیٹا سینٹر فعالیت برقرار بروقت پروکیورمنٹس یقینی ذمے داری سونپی گئی۔

In [ ]:

from gensim.corpora import Dictionary
from typing import List

def create_vocabulary(documents, save_to: str = None) -> List[str]:

    dataset=[[word for word in str(document).split()] for document in documents]
    vocab = Dictionary(documents=dataset)
    word_list = [key for key in vocab.token2id.keys() if len(key) > 1]
    print(len(word_list))
    if save_to:
        with open(f"{save_to}/vocabulary.txt", 'w') as txt:
            for word in word_list:
                txt.write(word + '\n')
    return word_list

In [ ]:
create_vocabulary(documents, save_to="sample_data")

21394

['آباد',
 'اثاثہ',
 'اربوں',
 'استعمال',
 'اسلام',
 'اسٹرکچرل',
 'اضافے',
 'اعتماد',
 'امور',
 'انتہائی',
 'اوسطاً',
 'آف',
 'ایسوسی',
 'ایشن',
 'ایشیا',
 'اے',
 'باعث',
 'بجائے',
 'براہ',
 'بلند',
 'بیس',
 'تجاویز',
 'تجویز',
 'تشخیص',
 'تمام',
 'توسیع',
 'جات',
 'جانب',
 'جانچ',
 'جمع',
 'جی',
 'حکام',
 'خزانہ',
 'خطے',
 'دہندگان',
 'دہندہ',
 'راست',
 'رفتار',
 'روپے',
 'ریفارمز',
 'ریٹرن',
 'سرٹیفائیڈاکاؤئنٹنٹس',
 'سطح',
 'سنجیدگی',
 'سی',
 'سیلز',
 'شامل',
 'شرح',
 'ضرورت',
 'عوام',
 'فیصد',
 'قریب',
 'قومی',
 'متبادل',
 'نادرا',
 'نتیجے',
 'نظام',
 'نقصان',
 'ودہولڈنگ',
 'ٹو',
 'ٹیکس',
 'ٹیکسیشن',
 'پاکستان',
 'پڑتال',
 'پی',
 'چارٹرڈ',
 'چاہیے۔',
 'چوری',
 'ڈائریکٹ',
 'ڈی',
 'ڈیٹا',
 'کارپوریٹ',
 'کرائی',
 'کہاگیا',
 'کیاگیا',
 'کیلیے',
 'ہندسی',
 'ہیں۔',
 'یک',
 'اجلاس',
 'اربکروڑ',
 'انتظامات',
 'اوراس',
 'اوراسکے',
 'اورکسٹمز',
 'اورکنسائنمنٹس',
 'آئندہ',
 'آئی',
 'آر',
 'آرنے',
 'آرڈر',
 'آرکے',
 'آفیسر',
 'آٹومیشن',
 'آپریشنز',
 'اپریل',
 'اہم',
 'ایف',
 'ایکسپریس',
 'ایگزیکٹو',
 'بارے',
 'باکس',
 'برقرار',
 'بروقت',
 'بریک',
 'بنایا',
 'بورڈ',
 'بوک',
 'بچا',
 'بڑے',
 'بی',
 'تفصیلی',
 'جائزہ',
 'جاری',
 'جاسکے۔',
 'جنرل',
 'حساب',
 'خصوصی',
 'خلل',
 'داری',
 'درآمدی',
 'درخواست',
 'دستاویز',
 'دستاویزکے',
 'دستیاب',
 'دسمبر',
 'ذرائع',
 'ذمے',
 'ریونیو',
 'زائد',
 'زاہدکھوکھرکی',
 'زیرصدارت',
 'سونپی',
 'سکے۔',
 'سینٹر',
 'سینٹرز',
 'سینٹرزکی',
 'سیکریٹریٹ',
 'صورتحال',
 'عائد',
 'فعالیت',
 'فنڈ',
 'فوری',
 'فی',
 'فیس',
 'فیصلہ',
 'فیصلے',
 'قائم',
 'قابو',
 'قبل',
 'لمیٹڈ',
 'مالیت',
 'مد',
 'مطابق',
 'ممبر',
 'موجود',
 'میںاس',
 'نمبر',
 'نمٹنے',
 'نیٹ',
 'ورک',
 'وی',
 'ویڈیوکانفرنس',
 'ٹی',
 'پانے',
 'پرال',
 'پروسیسنگ',
 'پروکیورمنٹس',
 'پیدا',
 'پیمانے',
 'چیف',
 'ڈاؤن',
 'ڈالرفراہم',
 'ڈاون',
 'ڈکلیئریشن',
 'کال',
 'کانفرنس',
 'کراچی',
 'کردہ',
 'کسٹمز',
 'کسٹمزکراچی',
 'کلیئرنس',
 'کنسائنمنٹ',
 'کنسائنمنٹس',
 'کوارٹرز',
 'کونسل',
 'گئی۔',
 'گا۔',
 'گریڈیشن',
 'گڈز',
 'ہاؤس',
 'ہزار',
 'ہفتے',
 'ہنگامی',
 'ہوچکا',
 'ہیڈ',
 'ہے۔',
 'یقینی',
 'اختتام',
 'ادریسسابق',
 'اراکین',
 'اسٹالز',
 'اعزاز',
 'اعلان',
 'افراد',
 'انڈسٹری',
 'انڈونیشیا',
 'او',
 'آئند',
 'آن',
 'اکیڈمی',
 'اہتمام',
 'ایم',
 'اینڈ',
 'ایکسپو',
 'برائےمائی',
 'بزنس',
 'بشیر',
 'بن',
 'بڑا',
 'بڑھا',
 'بھرے',
 'بہترین',
 'ترکیسری',
 'تشہیر',
 'تعداد',
 'تقریباً',
 'تھائی',
 'تھےہم',
 'تھے۔',
 'تیلی',
 'حالیہ',
 'حصہ',
 'حنیفخصوصی',
 'خالق',
 'خطاب',
 'خلیل',
 'خوش',
 'درمیان',
 'دن',
 'دوران',
 'ذکییونس',
 'روز',
 'رومانیہ',
 'ریحان',
 'رینجرز',
 'زبردست',
 'زبیر',
 'زیر',
 'سال',
 'سراج',
 'سراہتے',
 'سندھ',
 'سینئر',
 'شرکت',
 'شناخت',
 'صدر',
 'صدور',
 'طاہر',
 'عبدالباسط',
 'عبدالرزاق',
 'عبداللہ',
 'عطا',
 'غیر',
 'غیرملکی',
 'فارم',
 'فلپائن',
 'قاسم',
 'لاکھ',
 'لنکاویتنام',
 'لیا۔',
 'لینڈ',
 'مائی',
 'محمد',
 'مدنظر',
 'مصنوعات',
 'مفسر',
 'مقامی',
 'ملائیشیا',
 'ملک',
 'ملکی',
 'ممکنات',
 'منعقد',
 'منیجنگ',
 'موتی',
 'موقع',
 'مکمل',
 'مہیا',
 'میرین',
 'مین',
 'نائب',
 'نمائش',
 'نیوی',
 'وائس',
 'والاکے',
 'ویں',
 'پذیرائی',
 'پریس',
 'پلیٹ',
 'پولیس',
 'چیئرمین',
 'چیمبر',
 'کامرس',
 'کراچینمائش',
 'کمیٹی',
 'کنندگان',
 'کہاکہ',
 'کیو',
 'گرمی',
 'گروپ',
 'گزشتہ',
 'ہالز',
 'ہوگی',
 'یوکرین',
 'ابتدائی',
 'اثرات',
 'ارب',
 'اربکروڑلاکھ',
 'اسپورٹس',
 'اشیا',
 'اضافہ',
 'امپورٹ',
 'انجینئرنگ',
 'آسکی۔',
 'آلات',
 'آنے',
 'ایکسپورٹ',
 'ایگریکلچرل',
 'برآمدات',
 'برآمدی',
 'برعکس',
 'بڑھ',
 'تانومبر',
 'تجارتی',
 'تیزی',
 'جراحی',
 'جولائی',
 'حالانکہ',
 'خام',
 'خسارہ',
 'خسارے',
 'خوراک',
 'درآمدات',
 'دھندلا',
 'رواں',
 'رہاجبکہ',
 'رہا۔',
 'ریڈی',
 'ریکوری',
 'زرعی',
 'ظاہر',
 'فارما',
 'مارچ',
 'مالی',
 'ماہ',
 'مثبت',
 'محدود',
 'مشینری',
 'مقابلے',
 'منگوائی',
 'میڈ',
 'نمایاں',
 'نٹ',
 'واضح',
 'وریفائن',
 'وسبزیوں',
 'وٹیکسٹائل',
 'وکیمیائی',
 'ویئرکروڑ',
 'ٹرانسپورٹ',
 'ٹھوس',
 'پروڈکٹس',
 'پٹرولیم',
 'پھل',
 'پہنچ',
 'چاول',
 'چمڑے',
 'چینی',
 'ڈالر',
 'ڈالرکے',
 'کروڑ',
 'کروڑاور',
 'کروڑلاکھ',
 'کروڑکا',
 'کمی',
 'کیمیکلز',
 'گئیں',
 'گئیں۔',
 'گارمنٹس',
 'گوشت',
 'گڑ',
 'ہوسکے۔',
 'یااربکروڑ',
 'احمد',
 'اختر',
 'اخراجات',
 'ادائیگی',
 'ادارے',
 'ادوار',
 'ارشاد',
 'استحکام',
 'اسد',
 'اسلامک',
 'اشفاق',
 'افسران',
 'افضل',
 'اقدامات',
 'امکانات',
 'انسٹی',
 'انعقاد',
 'انوسٹمنٹ',
 'اورکسی',
 'آئیں',
 'آئے',
 'آباد',
 'آتا۔',
 'آزادتجارتی',
 'آمد',
 'آمدنی',
 'آڈٹ',
 'آگے',
 'اٹھایاہے',
 'اکاؤنٹینٹ',
 'اکاؤٹنٹس',
 'اکانومسٹ',
 'اکاوئنٹ',
 'ای',
 'ایس',
 'ایمنسٹی',
 'ایوب',
 'ایڈوائزر',
 'بات',
 'باہر',
 'بجلی',
 'بجٹ',
 'بحیثیت',
 'برائے',
 'برداشت',
 'برس',
 'برسوںسے',
 'بریکس',
 'بغیر',
 'بنکوں',
 'بچنے',
 'بڑھنا',
 'بہتر',
 'بہتری',
 'بیرون',
 'بینک',
 'تبادلہ',
 'تجارت',
 'ترغیب',
 'ترقی',
 'ترقیاتی',
 'تعلق',
 'تعیناتی',
 'تنخواہ',
 'توجہ',
 'تولہ',
 'تھا۔',
 'تیار',
 'تیسرے',
 'تین',
 'جارہی',
 'جاوید',
 'جاہ',
 'حسب',
 'حسن',
 'حسین',
 'حقیقت',
 'حل',
 'حوالے',
 'حکومت',
 'خاتمے',
 'خان',
 'ختم',
 'خرم',
 'دار',
 'دفاعی',
 'دنوں',
 'دنیا',
 'دنیابھر',
 'دنیاکے',
 'دوسرے',
 'رانا',
 'رجحان',
 'رضاکارانہ',
 'روایت',
 'رکن',
 'رہنا',
 'رہیں۔',
 'ریسرچ',
 'ریسرچر',
 'ریٹڈ',
 'زمان',
 'زمرے',
 'زمیندار',
 'سابق',
 'سابقہ',
 'ساتھ',
 'سازی',
 'سرمایہ',
 'سروس',
 'سمجھ',
 'سمیت',
 'سکتیں۔',
 'سکیم',
 'سیاسی',
 'سیر',
 'سیشن',
 'سیشنز',
 'سیمینار',
 'سینیٹر',
 'سیکرٹری',
 'شاہد',
 'شخص',
 'شعبوں',
 'شعبے',
 'شیخ',
 'صنعت',
 'صنعتی',
 'طبقے',
 'ظفر',
 'عابد',
 'عامر',
 'عدم',
 'عرفان',
 'عمر',
 'فائدہ',
 'فائلر',
 'فائلرز',
 'فنانس',
 'فنڈز',
 'فیڈرل',
 'قابل',
 'قارئین',
 'قانون',
 'قدر',
 'قوم',
 'قیادت',
 'لانے',
 'لوگ',
 'لگائے',
 'لیتاہے',
 'مبنی',
 'متاثر',
 'محض',
 'مختلف',
 'مرتب',
 'مرتبہ',
 'مزید',
 'مستقل',
 'مسعود',
 'مشکل',
 'مشیر',
 'مضبوط',
 'مطابقت',
 'معاہدوں',
 'معلومات',
 'معیشت',
 'ملنا',
 'ملٹی',
 'ملیں',
 'ممالک',
 'مملکت',
 'منصوبوں',
 'مہمان',
 'مہمانان',
 'میرے',
 'میڈلسٹ',
 'میڈیا',
 'میںسابق',
 'نئے',
 'نا',
 'ناانصافی',
 'نافذ',
 'نان',
 'ندیم',
 'نذر',
 'نزدیک',
 'نعیم',
 'نوٹس',
 'نیب',
 'نیشنل',
 'واپس',
 'وحید',
 'ورلڈ',
 'وزیر',
 'وزیراعظم',
 'وفاقی',
 'وقار',
 'ٹیوٹ',
 'ٹیکسوں',
 'ٹیکسٹائل',
 'پبلک',
 'پروگراموں',
 'پرویز',
 'پری',
 'پہلا',
 'پہلوؤں',
 'پہلے',
 'پیداوار',
 'پیداواری',
 'پیسہ',
 'چٹھہ',
 'ڈاکٹر',
 'ڈر',
 'کار',
 'کارکردگی',
 'کاری',
 'کامیاب',
 'کردیا',
 'کرسکتی۔',
 'کرسکی',
 'کرناہے۔',
 'کرنٹ',
 'کمپنی',
 'کمپنیاں',
 'کمیشن',
 'کوئی',
 'کواچھی',
 'کوٹیکس',
 'کیاجائے',
 'کیاجارہاہے',
 'کیاگیاتاہم',
 'گرامی',
 'گفتگو',
 'گولڈ',
 'گی۔',
 'گے۔',
 'ہارون',
 'ہدف',
 'ہراساں',
 'ہراسگی',
 'ہوجائے',
 'ہوٹل',
 'ہوپائے',
 'ہیں۔کسی',
 'ہے۔ایمنسٹی',
 'ہے۔مختلف',
 'یافتہ',
 'یوسف',
 'اسٹیٹ',
 'اظہار',
 'اظہارکرتے',
 'امریکی',
 'امکان',
 'انٹر',
 'انٹربینک',
 'اورروپے',
 'اوپن',
 'آغاز',
 'ایکس',
 'باوجوداوپن',
 'بتدریج',
 'بڑھتی',
 'بڑھی۔',
 'تا',
 'تسلسل',
 'تشویش',
 'تھی۔',
 'جویومیہ',
 'دگنی',
 'دیا۔',
 'رد',
 'سلسلہ',
 'سپورٹ',
 'سیزن',
 'شروع',
 'صورت',
 'طلب',
 'علاوہ',
 'عمرہ',
 'عندیہ',
 'عوامل',
 'غور',
 'فراہم',
 'فرق',
 'قدرروپے',
 'قیمت',
 'مارکیٹ',
 'مداخلت',
 'مستحکم',
 'مشتمل',
 'ملاقات',
 'ملین',
 'موجودہ',
 'مہنگا',
 'نسبت',
 'نمائندوں',
 'وفد',
 'پراسٹیٹ',
 'پراپرٹی',
 'پرمستحکم',
 'پڑنے',
 'پیر',
 'پیسے',
 'چاہیے',
 'چینج',
 'ڈالرز',
 'ڈالرودیگر',
 'ڈالرکی',
 'کابھی',
 'کاروں',
 'کرنسی',
 'کرنسیوں',
 'کمپنیوں',
 'کونئے',
 'کیاہے',
 'گیاہے',
 'گیا۔',
 'ہدایت',
 'یومیہ',
 'آج',
 'اسماعیل',
 'اسمبلی',
 'اعداد',
 'این',
 'تیاری',
 'سترسال',
 'شمارکوحتمی',
 'شکل',
 'صدارت',
 'مثال',
 'مفتاح',
 'وزارت',
 'پیش',
 'چار',
 'کردی',
 'آئیں',
 'ابتر',
 'ادارہ',
 'ازکم',
 'اسنارکل',
 'اسٹیشن',
 'اسٹیشنز',
 'اسٹیشنوں',
 'اسکیمیں',
 'اعظم',
 'اقبال',
 'الاؤنسز',
 'انفرااسٹرکچر',
 'انھیں',
 'اورسال',
 'اوورہیڈ',
 'آبادی',
 'آتشزدگی',
 'آراستہ',
 'آل',
 'آگ',
 'اڈہ',
 'اکثر',
 'اگست',
 'ایسوی',
 'ایمرجنسی',
 'باؤزر',
 'بالائی',
 'بتایا',
 'بجھانے',
 'برسوں',
 'بریگیڈ',
 'بلدیہ',
 'بنیادوں',
 'بولٹن',
 'بھرا',
 'بہبود',
 'بے',
 'تباہ',
 'تحت',
 'تربیت',
 'تعمیر',
 'جائیں',
 'جائیں۔',
 'جارہے',
 'جدید',
 'حال',
 'حالت',
 'حالی',
 'حفاظتی',
 'حکومتوں',
 'خاقان',
 'خراب',
 'خریداری',
 'خریدی',
 'خطوط',
 'خود',
 'دس',
 'دورے',
 'دکھا',
 'ذوالفقار',
 'رونما',
 'ریسکیو',
 'ریڈیو',
 'زحمی',
 'زخمی',
 'سالانہ',
 'سانحہ',
 'سانحے',
 'ساڑھے',
 'سبب',
 'سید',
 'سیکریٹری',
 'شاہ',
 'شمولیت',
 'شکار',
 'شہر',
 'صحیح',
 'صرف',
 'ضمن',
 'طریقے',
 'عارضی',
 'عالمی',
 'عباسی',
 'عظمیٰ',
 'علاج',
 'عمل',
 'غیرمعمولی',
 'فائر',
 'فائرفائٹرز',
 'فائنٹنگ',
 'فائٹرز',
 'فراہمی',
 'فعال',
 'فلاح',
 'قرار',
 'قریبی',
 'لاوارث',
 'لگنے',
 'لیےارب',
 'مانگی',
 'ماڑی',
 'مجموعی',
 'محکمہ',
 'مختص',
 'مشاورت',
 'مطالبہ',
 'معمار',
 'معیار',
 'مقامات',
 'ممستحکم',
 'منصوبے',
 'منظور',
 'منیجر',
 'موبائل',
 'نومبر',
 'نگرانی',
 'نہایت',
 'واقعات',
 'وبیشتر',
 'وجوہات',
 'ورکرز',
 'وقت',
 'وہیکل',
 'وین',
 'ٹاؤن',
 'ٹرک',
 'ٹنیڈرز',
 'ٹینڈر',
 'ٹینڈرز',
 'ٹینک',
 'ٹینکرز',
 'پاس',
 'پاسکے۔',
 'پانی',
 'پلاننگ',
 'پور',
 'پڑتا',
 'پڑے',
 'پیکیج',
 'چنہ',
 'چھوڑ',
 'ڈیولپمنٹ',
 'کارروائی',
 'کرتی۔',
 'کردیے',
 'کردیے۔',
 'کرلیے',
 'کمانڈ',
 'کنٹریکٹرز',
 'کوفائر',
 'کھڑی',
 'کہاہے',
 'گاڑیوں',
 'گلشن',
 'گیلن',
 'ہائیڈرنٹس',
 'ہوجاتے',
 'ہونگی۔',
 'یارومددگار',
 'ار',
 'اسٹریٹجک',
 'اقدام',
 'انھوںنے',
 'آگئیں۔',
 'اپنائی',
 'بتایاکہ',
 'برآمدا',
 'بعدوہ',
 'بنایاجائے',
 'بڑھایاجائے',
 'بڑی',
 'تحفظ',
 'ترجمان',
 'تناسب',
 'تناظر',
 'جائے۔',
 'جار',
 'حجم',
 'حوصلہ',
 'خاص',
 'داروں',
 'دلانے',
 'رابطہ',
 'رکھاجائے',
 'ریگولیٹری',
 'سلسلے',
 'شراکت',
 'شکنی',
 'طریقہ',
 'عرصہ',
 'عرصے',
 'فروغ',
 'لائنز',
 'لائی',
 'لاگت',
 'لبرالائزیشن',
 'متعدد',
 'متعلقہ',
 'مدت',
 'مدد',
 'مراحل',
 'مراعات',
 'مرحلہ',
 'مسابقت',
 'مسابقتی',
 'معیشتوں',
 'مقررہ',
 'ملنے',
 'منفی',
 'وار',
 'ٹیرف',
 'ٹیکسز',
 'پالیسی',
 'چند',
 'ڈیوٹیز',
 'کوشش',
 'کیاگیاہے',
 'کیاہے۔',
 'گرتی',
 'گزرنے',
 'گیاہے۔',
 'ہوا۔',
 'اداروں',
 'اعتراضات',
 'اکاؤنٹ',
 'اکاؤنٹس',
 'بالغ',
 'ترکی',
 'جنوبی',
 'خدشات',
 'رپورٹ',
 'رکھتی۔',
 'ریکارڈ',
 'مالیاتی',
 'مذہبی',
 'والوں',
 'چین',
 'کھلوانے',
 'ہولڈرز',
 'اتھارٹی',
 'اسپیڈ',
 'انڈ',
 'اورملتان',
 'اورکے',
 'ایریا',
 'تخمینہ',
 'تعمیراتی',
 'تکمیل',
 'تی',
 'رفتا',
 'زے',
 'سکھر',
 'سکھرملتان',
 'سکے',
 'علا',
 'فاصلوں',
 'لائن',
 'ملتان',
 'موٹر',
 'موٹرو',
 'موٹروے',
 'وے',
 'ٹریفک',
 'ٹول',
 'پذیر',
 'پرانٹر',
 'پل',
 'پلا',
 'چل',
 'چھوٹے',
 ...]

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(documents)

In [ ]:
vocab=vectorizer.get_feature_names_out()
for i in range(1,200):
  print(vocab[i])

ءبچہ
ءسے
ءمیں
ءکو
ءی
آءی
آؤ
آؤٹ
آؤٹس
آؤڈ
آؤں
آؤے
آئ
آئر
آئرس
آئرش
آئرلینڈ
آئرن
آئرننگ
آئرین
آئزک
آئس
آئسولیشن
آئسولیٹ
آئفی
آئل
آئلنگ
آئلینڈ
آئن
آئند
آئندامر
آئندہ
آئندہے
آئوٹ
آئوں
آئين
آئٹم
آئٹمز
آئی
آئیانہوں
آئیتو
آئیحمزہ
آئیر
آئیز
آئیسو
آئیسولیشن
آئیلا
آئین
آئیند
آئیندہ
آئینوں
آئینہ
آئینی
آئینے
آئیوا
آئیووا
آئیوی
آئیٹمز
آئیڈئل
آئیڈنٹیفکیشن
آئیڈیا
آئیڈیاز
آئیڈیل
آئیڈینٹیفکیشن
آئیکمسٹ
آئیکنایوارڈ
آئیکون
آئیگا
آئیگی
آئیں
آئیںایف
آئیے
آئے
آئےآئی
آئےاس
آئےجس
آئےضمنی
آئےلوٹا
آئےواضح
آئےگزشتہ
آئےہیںمحمد
آاور
آب
آبا
آباؤ
آبائو
آبائی
آباد
آباداور
آباداورصوابیشامل
آباداورہری
آبادباجوڑتورغرسفرہریپورمانسہرہکولائی
آبادباجوڑتورغرہریپورمانسہرہکولائی
آبادشہروں
آبادضلعی
آبادفروری
آبادفیصل
آبادلائسنس
آبادلیفٹیننٹسہیل
آبادمیڈیکل
آبادمیں
آبادنے
آبادٹوٹلاومیکرون
آبادپراپرٹی
آبادپشاور
آبادپولیس
آبادکا
آبادکاری
آبادکی
آبادکے
آبادہائیکورٹ
آبادی
آبادیوں
آبزرویشن
آبزور
آبشار
آبشارہے
آبشاریں
آبل
آبپارہ
آبپاشی
آبپاشیاں
آبپاشیوں
آبی
آبیاری
آبیانہ
آبیانہتاوان
آتا
آتش
آتشبازی
آتشزدگی
آتشی
آتشیں
آتی
آتیتفتیش
آتیہر
آتیہیں
آتے
آتےمیں
آتےہیں
آثار
آثاریات
آج
آجاؤ
آجاؤں
آجائیں
آجائیںانہوں
آجائے
آجائےوزارت
آجاتا
آجاتی
آجاتے
آجانا
آجاو
آجر
آجروں
آجکل
آجکلیم
آخال
آخر
آخرت
آخرمیں
آخرکار
آخری
آداب
آدانا
آدتیا
آدلوگی
آدم
آدمی
آدھ
آدھا
آدھاکر
آدھاگھنٹا
آدھی
آدھے
آذادی
آذربائیجان
آر
آرا
آراء
آرائش
آرائی
آرائیاں
آرائیوں
آرائیں
آراز
آراستہ
آراستہیہ
آرام
آرامدہ
آرامکو
آراو
آراومانگ
آرایس
آرایچ
آراے
آربٹ
آرتمیس

In [ ]:
with open("vocabulary.txt", "w") as f :
    f.write("\n".join(map(str, vocab)))
f.close()

In [ ]:
print(len(vocab))

46565